### ISSUE TITLE
Panic in Blockchain::push_block

### ISSUE THREAD

**Issue by riptl** [nimiq/core-rs-albatross#101]
Branch: `devnet-rc3`.

Occurred during the first 100-validator cloud test.

Panic at https://github.com/nimiq/core-rs-albatross/blob/268664180025dea159af76b7bd81926a3168b7a3/blockchain-albatross/src/blockchain.rs#L697

#### Crash log

<details>
<summary>Panic</summary>

```
 2019-12-02 03:02:13.667 DEBUG sync                 | blockchain.push() took 30ms (0 txs)
 2019-12-02 03:02:16.470 DEBUG consensus_agent      | Accepted tx 525eea42fc5abf56d047a2b2b15715aab869211b3794f346de8ec57f38828784 from ws://7.0.0.238:8443/af54b271816d56ce2f2b2833d649e252
 2019-12-02 03:02:16.478 DEBUG consensus_agent      | Accepted tx 95dcf357e611024b2ec272a3100b62aea1ba275908dd23a1d6612c294de37f85 from ws://7.0.0.238:8443/af54b271816d56ce2f2b2833d649e252
 2019-12-02 03:02:20.862 DEBUG blockchain           | Rebranching to fork 69afd4f93d614870c556686faf55299743bfca2428c2853a4ae479695f65e9e7, height #27185, view number 6
 2019-12-02 03:02:20.862 DEBUG blockchain           | Found common ancestor 335655801f3d89eedd6f9cf1d1bb8709b7aec1a11ef20f9c92dff2c7376510e2 at height #27184, 1 blocks up
 2019-12-02 03:02:20.865 DEBUG blockchain           | Slash inherent: view change: NQ54 XYRY HT58 NAU8 RDFR H7KD X0YQ SFQL 4ACY
thread 'tokio-runtime-worker-1' panicked at 'internal error: entered unreachable code', blockchain-albatross/src/blockchain.rs:697:36
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1024
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: std::panicking::begin_panic
  12: nimiq_blockchain_albatross::blockchain::Blockchain::push_block
  13: <nimiq_blockchain_albatross::blockchain::Blockchain as nimiq_blockchain_base::AbstractBlockchain>::push
  14: <nimiq_consensus::consensus_agent::sync::FullSync<B> as nimiq_consensus::consensus_agent::sync::SyncProtocol<B>>::on_block
  15: nimiq_consensus::inventory::InventoryAgent<P>::on_block
  16: <F as nimiq_utils::observer::PassThroughListener<E>>::on_event
  17: nimiq_utils::observer::PassThroughNotifier<E>::notify
  18: nimiq_messages::MessageNotifier::notify
  19: <F as nimiq_utils::observer::PassThroughListener<E>>::on_event
  20: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  21: futures::future::chain::Chain<A,B,C>::poll
  22: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  23: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  24: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  25: futures::task_impl::std::set
  26: futures::task_impl::Spawn<T>::poll_future_notify
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:81
  29: tokio_threadpool::task::Task::run
  30: tokio_threadpool::worker::Worker::run_task
  31: tokio_threadpool::worker::Worker::run
  32: tokio_timer::clock::clock::with_default
  33: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  34: std::thread::local::LocalKey<T>::with
  35: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 2019-12-02 03:02:21.137 INFO  nimiq_client         | Head: #27272 - 7f65e610dee399e0ee543439a125ee5c557119c6daa028a2ee2f9583f991fe7e, Peers: 62
 2019-12-02 03:02:23.670 DEBUG validator_network    | New view change for: #27273.2, node_id=18
 2019-12-02 03:02:23.670 INFO  validator            | Starting view change to #27273.2
 2019-12-02 03:02:24.724 DEBUG sink                 | Closing connection, reason: SendFailed (Some("SendFailed"))
```

</details>

**Comment by jgraef** [comment]
![20200511_165008](https://user-images.githubusercontent.com/159282/81575865-d0324b80-93a7-11ea-8cdb-7f873a13fc18.jpg)

There is a `rebranch` to a block in a finalized epoch. The second loop in `rebranch` will iterate over the macro block.
The first loop checks that the fork doesn't include a macro-block. ~~But I see no issue with a fork including a macro-block.~~ This actually can't happen, since any macro blocks we accepted must be on the main chain.

~~So the assertion in the first loop should be removed~~. Then we should check if the ancestor is in the current epoch.
