### ISSUE TITLE
Failure in devnet execution during slot calculation in RPC interface

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#1025]

**Comment by jsdanielh** [comment]
Error log:
```
Jul 23 07:58:56 seed1 nimiq-client[53168]: 2022-07-23T07:58:56.960551Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Couldn't calculate slot owner!': rpc-interface/src/types.rs:375
Jul 23 07:58:56 seed1 nimiq-client[53168]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Jul 23 07:58:56 seed1 nimiq-client[53168]:    1: log_panics::Config::install_panic_hook::{{closure}}
Jul 23 07:58:56 seed1 nimiq-client[53168]:    2: std::panicking::rust_panic_with_hook
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:702:17
Jul 23 07:58:56 seed1 nimiq-client[53168]:    3: std::panicking::begin_panic_handler::{{closure}}
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:588:13
Jul 23 07:58:56 seed1 nimiq-client[53168]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/sys_common/backtrace.rs:138:18
Jul 23 07:58:56 seed1 nimiq-client[53168]:    5: rust_begin_unwind
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:584:5
Jul 23 07:58:56 seed1 nimiq-client[53168]:    6: core::panicking::panic_fmt
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:142:14
Jul 23 07:58:56 seed1 nimiq-client[53168]:    7: core::panicking::panic_display
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:72:5
Jul 23 07:58:56 seed1 nimiq-client[53168]:    8: core::panicking::panic_str
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:56:5
Jul 23 07:58:56 seed1 nimiq-client[53168]:    9: core::option::expect_failed
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/option.rs:1874:5
Jul 23 07:58:56 seed1 nimiq-client[53168]:   10: nimiq_rpc_interface::types::Block::from_block
Jul 23 07:58:56 seed1 nimiq-client[53168]:   11: nimiq_rpc_server::dispatchers::blockchain::get_block_by_hash
Jul 23 07:58:56 seed1 nimiq-client[53168]:   12: <T as futures_util::fns::FnMut1<A>>::call_mut
Jul 23 07:58:56 seed1 nimiq-client[53168]:   13: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
Jul 23 07:58:56 seed1 nimiq-client[53168]:   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 23 07:58:56 seed1 nimiq-client[53168]:   15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Jul 23 07:58:56 seed1 nimiq-client[53168]:   16: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 23 07:58:56 seed1 nimiq-client[53168]:   17: std::thread::local::LocalKey<T>::with
Jul 23 07:58:56 seed1 nimiq-client[53168]:   18: tokio::runtime::thread_pool::worker::Context::run_task
Jul 23 07:58:56 seed1 nimiq-client[53168]:   19: tokio::runtime::thread_pool::worker::Context::run
Jul 23 07:58:56 seed1 nimiq-client[53168]:   20: tokio::macros::scoped_tls::ScopedKey<T>::set
Jul 23 07:58:56 seed1 nimiq-client[53168]:   21: tokio::runtime::thread_pool::worker::run
Jul 23 07:58:56 seed1 nimiq-client[53168]:   22: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Jul 23 07:58:56 seed1 nimiq-client[53168]:   23: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 23 07:58:56 seed1 nimiq-client[53168]:   24: tokio::runtime::blocking::pool::Inner::run
Jul 23 07:58:56 seed1 nimiq-client[53168]:   25: std::sys_common::backtrace::__rust_begin_short_backtrace
Jul 23 07:58:56 seed1 nimiq-client[53168]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jul 23 07:58:56 seed1 nimiq-client[53168]:   27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1951:9
Jul 23 07:58:56 seed1 nimiq-client[53168]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1951:9
Jul 23 07:58:56 seed1 nimiq-client[53168]:       std::sys::unix::thread::Thread::new::thread_start
Jul 23 07:58:56 seed1 nimiq-client[53168]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/sys/unix/thread.rs:108:17
Jul 23 07:58:56 seed1 nimiq-client[53168]:   28: start_thread
Jul 23 07:58:56 seed1 nimiq-client[53168]:   29: clone
Jul 23 07:58:56 seed1 nimiq-client[53168]:
```
