### ISSUE TITLE
Panic in `zkp_prover`

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#1162]
In the latest devnet run a panic appeared in the prover node in `zkp_prover`:
```
Nov 30 10:38:16 prover1 nimiq-client[83122]: 2022-11-30T10:38:16.457688Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'The current state should never lag behind more than one epoch': core-rs-albatross/zkp-component/src/zkp_prover.rs:120
Nov 30 10:38:16 prover1 nimiq-client[83122]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Nov 30 10:38:16 prover1 nimiq-client[83122]:    1: log_panics::Config::install_panic_hook::{{closure}}
Nov 30 10:38:16 prover1 nimiq-client[83122]:    2: std::panicking::rust_panic_with_hook
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:702:17
Nov 30 10:38:16 prover1 nimiq-client[83122]:    3: std::panicking::begin_panic_handler::{{closure}}
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:586:13
Nov 30 10:38:16 prover1 nimiq-client[83122]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/sys_common/backtrace.rs:138:18
Nov 30 10:38:16 prover1 nimiq-client[83122]:    5: rust_begin_unwind
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:584:5
Nov 30 10:38:16 prover1 nimiq-client[83122]:    6: core::panicking::panic_fmt
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/core/src/panicking.rs:142:14
Nov 30 10:38:16 prover1 nimiq-client[83122]:    7: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
Nov 30 10:38:16 prover1 nimiq-client[83122]:    8: futures_util::stream::stream::StreamExt::poll_next_unpin
Nov 30 10:38:16 prover1 nimiq-client[83122]:    9: <nimiq_zkp_component::zkp_component::ZKPComponent<N> as core::future::future::Future>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Nov 30 10:38:16 prover1 nimiq-client[83122]:   11: tokio::runtime::task::core::Core<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   12: tokio::runtime::task::harness::Harness<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   13: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Nov 30 10:38:16 prover1 nimiq-client[83122]:   14: tokio::runtime::scheduler::multi_thread::worker::Context::run
Nov 30 10:38:16 prover1 nimiq-client[83122]:   15: tokio::macros::scoped_tls::ScopedKey<T>::set
Nov 30 10:38:16 prover1 nimiq-client[83122]:   16: tokio::runtime::scheduler::multi_thread::worker::run
Nov 30 10:38:16 prover1 nimiq-client[83122]:   17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Nov 30 10:38:16 prover1 nimiq-client[83122]:   18: tokio::runtime::task::core::Core<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   19: tokio::runtime::task::harness::Harness<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   20: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 30 10:38:16 prover1 nimiq-client[83122]:   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 30 10:38:16 prover1 nimiq-client[83122]:   22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/alloc/src/boxed.rs:1935:9
Nov 30 10:38:16 prover1 nimiq-client[83122]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/alloc/src/boxed.rs:1935:9
Nov 30 10:38:16 prover1 nimiq-client[83122]:       std::sys::unix::thread::Thread::new::thread_start
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/sys/unix/thread.rs:108:17
Nov 30 10:38:16 prover1 nimiq-client[83122]:   23: <unknown>
Nov 30 10:38:16 prover1 nimiq-client[83122]:   24: <unknown>
Nov 30 10:38:16 prover1 nimiq-client[83122]:

```

**Comment by paberr** [comment]
@ii-cruz Tried to run it on her machine and it worked. We will need more debugging info on this.

**Comment by paberr** [comment]
@jsdanielh @jeffesquivels We added additional debugging messages in b7674d892142fa1697488aa3c85d5593f4214e2e and will await the outcome.

**Comment by paberr** [comment]
Fixed
