### ISSUE TITLE
Panic in CI jobs: 'SinkImpl::poll_ready called after error.

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#1319]
This panic has been observed in some instances of our CI jobs:

[4079126152](https://github.com/nimiq/core-rs-albatross/actions/runs/4079126152)

Full panic trace:

```
:2023-02-02T22:51:14.38892844Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'SinkImpl::poll_ready called after error.': /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksink-0.1.2/src/lib.rs:158
./validator2.log:26702:   1: log_panics::Config::install_panic_hook::{{closure}}
./validator2.log:26703:             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.1.0/src/lib.rs:115:29
./validator2.log:26706:      std::panicking::rust_panic_with_hook
./validator2.log:26707:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:692:13
./validator2.log:26708:   3: std::panicking::begin_panic::{{closure}}
./validator2.log:26709:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:608:9
./validator2.log:26712:   5: std::panicking::begin_panic
./validator2.log:26713:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:607:12
./validator2.log:26794:  46: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
./validator2.log:26795:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panic/unwind_safe.rs:271:9
./validator2.log:26796:  47: std::panicking::try::do_call
./validator2.log:26797:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
./validator2.log:26799:  49: std::panicking::try
./validator2.log:26800:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
./validator2.log:26801:  50: std::panic::catch_unwind
./validator2.log:26802:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
./validator2.log:26843:  69: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
./validator2.log:26844:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panic/unwind_safe.rs:271:9
./validator2.log:26845:  70: std::panicking::try::do_call
./validator2.log:26846:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
./validator2.log:26848:  72: std::panicking::try
./validator2.log:26849:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
./validator2.log:26850:  73: std::panic::catch_unwind
./validator2.log:26851:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
./validator2.log:26874:  85: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
./validator2.log:26875:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panic/unwind_safe.rs:271:9
./validator2.log:26876:  86: std::panicking::try::do_call
./validator2.log:26877:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
./validator2.log:26879:  88: std::panicking::try
./validator2.log:26880:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
./validator2.log:26881:  89: std::panic::catch_unwind
./validator2.log:26882:             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
```

**Comment by viquezclaudio** [comment]
Observed here as well:
https://github.com/nimiq/core-rs-albatross/actions/runs/4117867549

**Comment by jsdanielh** [comment]
According to [this issue in libp2p](https://github.com/libp2p/rust-libp2p/issues/2598) we should update yamux to 0.10.2 (and we are at 0.10.1). This is being done in #1368.
