### ISSUE TITLE
Panic at RPC `get_slot_at`

### ISSUE THREAD

**Issue by onmax** [nimiq/core-rs-albatross#1454]
<details><summary>Logs from seed1</summary>
<p>

```Logs
Mar 21 19:07:16 seed1 nimiq-client[2472]: 2023-03-21T19:07:16.057799726Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Couldn't calculate slot owner!: BlockNotFound': rpc-interface/src/types.rs:352
Mar 21 19:07:16 seed1 nimiq-client[2472]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Mar 21 19:07:16 seed1 nimiq-client[2472]:    1: log_panics::Config::install_panic_hook::{{closure}}
Mar 21 19:07:16 seed1 nimiq-client[2472]:    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:2002:9
Mar 21 19:07:16 seed1 nimiq-client[2472]:       std::panicking::rust_panic_with_hook
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:692:13 
Mar 21 19:07:16 seed1 nimiq-client[2472]:    3: std::panicking::begin_panic_handler::{{closure}}
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:579:13 
Mar 21 19:07:16 seed1 nimiq-client[2472]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys_common/backtrace.rs:137:18
Mar 21 19:07:16 seed1 nimiq-client[2472]:    5: rust_begin_unwind
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/panicking.rs:575:5
Mar 21 19:07:16 seed1 nimiq-client[2472]:    6: core::panicking::panic_fmt
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/core/src/panicking.rs:64:14 
Mar 21 19:07:16 seed1 nimiq-client[2472]:    7: core::result::unwrap_failed
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/core/src/result.rs:1750:5
Mar 21 19:07:16 seed1 nimiq-client[2472]:    8: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_rpc_interface::blockchain::BlockchainInterface>::get_slot_at::{{closure}}
Mar 21 19:07:16 seed1 nimiq-client[2472]:    9: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Mar 21 19:07:16 seed1 nimiq-client[2472]:   10: <nimiq_jsonrpc_server::ModularDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Mar 21 19:07:16 seed1 nimiq-client[2472]:   11: <nimiq_jsonrpc_server::AllowListDispatcher<D> as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Mar 21 19:07:16 seed1 nimiq-client[2472]:   12: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   13: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   14: <warp::filter::and::AndFuture<T,U> as core::future::future::Future>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   15: <warp::filter::recover::RecoverFuture<T,F> as core::future::future::Future>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   16: scoped_tls::ScopedKey<T>::set
Mar 21 19:07:16 seed1 nimiq-client[2472]:   17: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
Mar 21 19:07:16 seed1 nimiq-client[2472]:   18: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
Mar 21 19:07:16 seed1 nimiq-client[2472]:   19: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Mar 21 19:07:16 seed1 nimiq-client[2472]:   21: tokio::runtime::task::core::Core<T,S>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   22: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   23: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Mar 21 19:07:16 seed1 nimiq-client[2472]:   24: tokio::runtime::scheduler::multi_thread::worker::Context::run
Mar 21 19:07:16 seed1 nimiq-client[2472]:   25: tokio::macros::scoped_tls::ScopedKey<T>::set
Mar 21 19:07:16 seed1 nimiq-client[2472]:   26: tokio::runtime::scheduler::multi_thread::worker::run
Mar 21 19:07:16 seed1 nimiq-client[2472]:   27: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Mar 21 19:07:16 seed1 nimiq-client[2472]:   28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once 
Mar 21 19:07:16 seed1 nimiq-client[2472]:   29: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 21 19:07:16 seed1 nimiq-client[2472]:   30: tokio::runtime::blocking::pool::Inner::run
Mar 21 19:07:16 seed1 nimiq-client[2472]:   31: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 21 19:07:16 seed1 nimiq-client[2472]:   32: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 21 19:07:16 seed1 nimiq-client[2472]:   33: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
Mar 21 19:07:16 seed1 nimiq-client[2472]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/alloc/src/boxed.rs:1988:9
Mar 21 19:07:16 seed1 nimiq-client[2472]:       std::sys::unix::thread::Thread::new::thread_start
Mar 21 19:07:16 seed1 nimiq-client[2472]:              at /rustc/7aa413d59206fd511137728df3d9e0fd377429bd/library/std/src/sys/unix/thread.rs:108:17
Mar 21 19:07:16 seed1 nimiq-client[2472]:   34: <unknown>
Mar 21 19:07:16 seed1 nimiq-client[2472]:   35: <unknown>
Mar 21 19:07:16 seed1 nimiq-client[2472]: 
```

</p>
</details> 

## Description

Making an  invalid request to `get_slot_at`, the RPC server returns nothing as you can see in the screenshot (empty response)

![image](https://user-images.githubusercontent.com/22072217/225988428-09c9b9dc-ce2d-4b1d-9193-2b5412a771c2.png)

## Solution

I would expect to see an error with code and message explaining the error (example of an invalid request)

![image](https://user-images.githubusercontent.com/22072217/225988321-99a89205-a950-46d5-94d1-d75d720b6f71.png)

**Comment by onmax** [comment]
@paberr @ii-cruz I added the logs in the issue

**Comment by paberr** [comment]
Thanks, it's indeed the panic. I'll fix it
