### ISSUE TITLE
Panic in tendermint: "'Preceding block must be a micro block and it must be known"

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#1463]
```
thread 'tokio-runtime-worker' panicked at 'Preceding block must be a micro block and it must be known.': /home/runner/work/core-rs-albatross/core-rs-albatross/validator/src/tendermint.rs:212
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:577:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14

```
[validator3.log](https://github.com/nimiq/core-rs-albatross/files/11012258/validator3.log)

Observed in CI run:
https://github.com/nimiq/core-rs-albatross/actions/runs/4462061565/jobs/7836338199

Logs attached

**Comment by viquezclaudio** [comment]
Another instance of this panic:
[CI](https://github.com/nimiq/core-rs-albatross/actions/runs/4555427550/jobs/8034460690)

**Comment by viquezclaudio** [comment]
Another instance of this panic:
[ci](https://github.com/nimiq/core-rs-albatross/actions/runs/4733420476)
