### ISSUE TITLE
Panic in testnet while rebranching/reverting blocks

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#1512]
Observed a panic in both a history node and a full node.
The nodes were trying to synchronize, and as part of the process they had to revert some blocks, and during this process, they panicked because of an inconsistent state between the accounts state and the block state root.

```
Mar 27 19:04:07 validator3 nimiq-client[2895]: 2023-03-27T19:04:07.730676282Z INFO  cluster              | Downloading history for epoch #7, batch set idx 0: 3072/6365 (48.26%)
Mar 27 19:04:07 validator3 nimiq-client[2895]: 2023-03-27T19:04:07.732716947Z INFO  cluster              | Downloading history for epoch #7, batch set idx 0: 4096/6365 (64.35%)
Mar 27 19:04:07 validator3 nimiq-client[2895]: 2023-03-27T19:04:07.734997716Z INFO  cluster              | Downloading history for epoch #7, batch set idx 0: 5120/6365 (80.44%)
Mar 27 19:04:07 validator3 nimiq-client[2895]: 2023-03-27T19:04:07.737234000Z INFO  cluster              | Downloading history for epoch #7, batch set idx 0: 6144/6365 (96.53%)
Mar 27 19:04:07 validator3 nimiq-client[2895]: 2023-03-27T19:04:07.737859075Z INFO  cluster              | Downloading history for epoch #7, batch set idx 0: 6365/6365 (100.00%)
Mar 27 19:04:07 validator3 nimiq-client[2895]: 2023-03-27T19:04:07.737896718Z DEBUG sync_stream          | Processing epoch #7 (6365 history items)
...
Mar 27 19:04:08 validator3 nimiq-client[2895]: 2023-03-27T19:04:08.334392883Z DEBUG history_sync         | Need to revert micro blocks from the current epoch num_blocks=8
Mar 27 19:04:08 validator3 nimiq-client[2895]: 2023-03-27T19:04:08.338502219Z DEBUG accounts             | Reverting block block_number=129609
Mar 27 19:04:08 validator3 nimiq-client[2895]: 2023-03-27T19:04:08.344596592Z DEBUG accounts             | Reverting block block_number=129608
Mar 27 19:04:08 validator3 nimiq-client[2895]: 2023-03-27T19:04:08.358397641Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
Mar 27 19:04:08 validator3 nimiq-client[2895]:   left: `adde71e0d97269e3287315ceaf9443144952a40640143bed6cc3eb982d41e5e7`,
Mar 27 19:04:08 validator3 nimiq-client[2895]:  right: `a79f96006b64d5cbb43a1ff801edc90a90051479e3b1f3f809148716e98b707f`: Failed to revert - inconsistent state': blockchain/src/blockchain/accounts.rs:155
Mar 27 19:04:08 validator3 nimiq-client[2895]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Mar 27 19:04:08 validator3 nimiq-client[2895]:    1: log_panics::Config::install_panic_hook::{{closure}}
Mar 27 19:04:08 validator3 nimiq-client[2895]:    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
Mar 27 19:04:08 validator3 nimiq-client[2895]:              at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/alloc/src/boxed.rs:2002:9
Mar 27 19:04:08 validator3 nimiq-client[2895]:       std::panicking::rust_panic_with_hook
Mar 27 19:04:08 validator3 nimiq-client[2895]:              at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:692:13
Mar 27 19:04:08 validator3 nimiq-client[2895]:    3: std::panicking::begin_panic_handler::{{closure}}
Mar 27 19:04:08 validator3 nimiq-client[2895]:              at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:579:13
Mar 27 19:04:08 validator3 nimiq-client[2895]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Mar 27 19:04:08 validator3 nimiq-client[2895]:              at /rustc/8460ca823e8367a30dda4
[pubtestnet_validator3.log](https://github.com/nimiq/core-rs-albatross/files/11082712/pubtestnet_validator3.log)
30efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:137:18
Mar 27 19:04:08 validator3 nimiq-client[2895]:    5: rust_begin_unwind
Mar 27 19:04:08 validator3 nimiq-client[2895]:              at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
Mar 27 19:04:08 validator3 nimiq-client[2895]:    6: core::panicking::panic_fmt
Mar 27 19:04:08 validator3 nimiq-client[2895]:              at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
Mar 27 19:04:08 validator3 nimiq-client[2895]:    7: core::panicking::assert_failed_inner
Mar 27 19:04:08 validator3 nimiq-client[2895]:    8: core::panicking::assert_failed
```

**Comment by viquezclaudio** [comment]
[pubtestnet_validator8.log](https://github.com/nimiq/core-rs-albatross/files/11082715/pubtestnet_validator8.log)
[pubtestnet_validator3.log](https://github.com/nimiq/core-rs-albatross/files/11082719/pubtestnet_validator3.log)
