### ISSUE TITLE
Panic at account's reserved balance

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#1520]
[This CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/4538650367) hit the following panic in validator 3:
```
[2m2023-03-28T03:13:13.552233092Z[0m [31mERROR[0m [2mpanic               [0m | thread 'tokio-runtime-worker' panicked at 'Tried to release more than was reserved (0.00100 > 0)': primitives/account/src/reserved_balance.rs:56
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.67/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   7: nimiq_account::reserved_balance::ReservedBalance::release_for::{{closure}}
             at primitives/account/src/reserved_balance.rs:56:13
   8: core::option::Option<T>::unwrap_or_else
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/option.rs:873:21
   9: nimiq_account::reserved_balance::ReservedBalance::release_for
             at primitives/account/src/reserved_balance.rs:55:24
  10: nimiq_account::reserved_balance::ReservedBalance::release
             at primitives/account/src/reserved_balance.rs:50:9
  11: <nimiq_account::account::basic_account::BasicAccount as nimiq_account::interaction_traits::AccountTransactionInteraction>::release_balance
             at primitives/account/src/account/basic_account.rs:146:9
  12: <nimiq_account::account::Account as nimiq_account::interaction_traits::AccountTransactionInteraction>::release_balance
             at primitives/account/src/account/mod.rs:265:9
  13: nimiq_account::accounts::Accounts::release_balance
             at primitives/account/src/accounts.rs:115:21
  14: nimiq_blockchain::blockchain::wrappers::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::release_balance
             at blockchain/src/blockchain/wrappers.rs:164:9
  15: nimiq_mempool::mempool_state::MempoolState::remove
             at mempool/src/mempool_state.rs:134:17
  16: nimiq_mempool::mempool::Mempool::mempool_update
             at mempool/src/mempool.rs:339:25
  17: nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork>::on_blockchain_extended
             at validator/src/validator.rs:508:13
  18: nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork>::on_blockchain_event
             at validator/src/validator.rs:473:52
  19: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
             at validator/src/validator.rs:870:13
  20: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:223:17
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  22: tokio::runtime::task::core::Core<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:212:13
  23: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panic/unwind_safe.rs:271:9
  25: std::panicking::try::do_call
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:483:40
  26: __rust_try
  27: std::panicking::try
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:447:19
  28: std::panic::catch_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panic.rs:140:14
  29: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  30: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  31: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  32: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  33: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  34: tokio::runtime::task::LocalNotified<S>::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/mod.rs:394:9
  35: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  36: tokio::runtime::coop::with_budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:73:5
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  37: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  38: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  39: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/macros/scoped_tls.rs:61:9
  40: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  41: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  42: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/task.rs:42:21
  43: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:223:17
  44: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  45: tokio::runtime::task::core::Core<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:212:13
  46: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  47: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panic/unwind_safe.rs:271:9
  48: std::panicking::try::do_call
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:483:40
  49: __rust_try
  50: std::panicking::try
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:447:19
  51: std::panic::catch_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panic.rs:140:14
  52: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  53: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  55: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  56: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  57: tokio::runtime::task::UnownedTask<S>::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/mod.rs:431:9
  58: tokio::runtime::blocking::pool::Task::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/pool.rs:159:9
  59: tokio::runtime::blocking::pool::Inner::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/pool.rs:511:17
  60: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/pool.rs:469:13
  61: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys_common/backtrace.rs:121:18
  62: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/thread/mod.rs:558:17
  63: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panic/unwind_safe.rs:271:9
  64: std::panicking::try::do_call
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:483:40
  65: __rust_try
  66: std::panicking::try
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:447:19
  67: std::panic::catch_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panic.rs:140:14
  68: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/thread/mod.rs:557:30
  69: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/ops/function.rs:250:5
  70: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/sys/unix/thread.rs:108:17
  71: <unknown>
  72: <unknown>
    
```

**Comment by jsdanielh** [comment]
Another instance of this issue: https://github.com/nimiq/core-rs-albatross/actions/runs/4570983626
