### ISSUE TITLE
Panic at tendermint

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#1533]
In [this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/4569482285/jobs/8065782222), validator 3 faced a panic in Tendermint with the following output:

```
2023-03-30T22:35:50.261247782Z DEBUG reward               | Computed the batch delay and penalty (if any) block_number=300 delay=36827 penalty=0.6124779695810886
2023-03-30T22:35:50.275537520Z DEBUG reward               | Computed the batch delay and penalty (if any) block_number=300 delay=36827 penalty=0.6124779695810886
2023-03-30T22:35:50.280884135Z DEBUG aggregate            | Aggregation resulted in Block polka round_and_step=(3, Precommit) proposal=1b860ff350d204455571d11514dc2c90fc0e80a35003ab2b14f092010f898247
2023-03-30T22:35:59.237111221Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code': /home/runner/work/core-rs-albatross/core-rs-albatross/tendermint/src/states/aggregate.rs:171
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.67/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:577:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   7: core::panicking::panic
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
   8: nimiq_tendermint::states::aggregate::<impl nimiq_tendermint::tendermint::Tendermint<TProtocol>>::on_polka
             at tendermint/src/states/aggregate.rs:171:32
   9: nimiq_tendermint::states::aggregate::<impl nimiq_tendermint::tendermint::Tendermint<TProtocol>>::aggregate
             at tendermint/src/states/aggregate.rs:76:13
  10: <nimiq_tendermint::tendermint::Tendermint<TProtocol> as futures_core::stream::Stream>::poll_next
             at tendermint/src/tendermint.rs:630:48
  11: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.26/src/stream/stream/map.rs:58:26
  12: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.26/src/stream.rs:120:9
  13: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  14: <nimiq_validator::macro::ProduceMacroBlock<TValidatorNetwork> as futures_core::stream::Stream>::poll_next
             at validator/src/macro.rs:148:9
  15: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.26/src/stream/stream/mod.rs:1625:9
  16: nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork>::poll_macro
             at validator/src/validator.rs:539:46
  17: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
             at validator/src/validator.rs:893:17
  18: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:223:17
  19: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  20: tokio::runtime::task::core::Core<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:212:13
  21: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  23: std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  24: __rust_try
  25: std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  26: std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  27: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  28: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  29: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  30: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  31: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  32: tokio::runtime::task::LocalNotified<S>::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/mod.rs:394:9
  33: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
  34: tokio::runtime::coop::with_budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:73:5
      tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  35: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  36: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  37: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/macros/scoped_tls.rs:61:9
  38: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  39: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  40: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/task.rs:42:21
  41: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:223:17
  42: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  43: tokio::runtime::task::core::Core<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/core.rs:212:13
  44: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  45: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  46: std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  47: __rust_try
  48: std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  49: std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  50: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  51: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  52: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  53: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:255:5
  54: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  55: tokio::runtime::task::UnownedTask<S>::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/task/mod.rs:431:9
  56: tokio::runtime::blocking::pool::Task::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/pool.rs:159:9
  57: tokio::runtime::blocking::pool::Inner::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/pool.rs:511:17
  58: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/blocking/pool.rs:469:13
  59: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:121:18
  60: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/mod.rs:558:17
  61: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  62: std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  63: __rust_try
  64: std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  65: std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  66: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/mod.rs:557:30
  67: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  68: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108:17
  69: <unknown>
  70: <unknown>
```

**Comment by styppo** [comment]
@nibhar Is this still relevant?
