### ISSUE TITLE
Deadlock when enabling auto-unpark config while being an active validator

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#157]
- My node was an active validator.
- I stopped it to change the config (while the chain was continuing without me)
- I added the
```
wallet_private_key = "..."
```
config in the `[validator]` section.
- I restarted the node, and it started syncing.
- It panicked at a deadlock:

```
 DEBUG consensus            | Syncing blockchain with peer ws://validator5.validators.devnet.nimiq.dev:8443/97decc3f1deef6e122af5ed0abe18df3
 DEBUG consensus            | Finished sync with peer ws://validator5.validators.devnet.nimiq.dev:8443/97decc3f1deef6e122af5ed0abe18df3
 DEBUG consensus            | Syncing blockchain with peer ws://validator6.validators.devnet.nimiq.dev:8443/135f94801b8e92a823d13d8f1292dbc4
 DEBUG consensus            | Finished sync with peer ws://validator6.validators.devnet.nimiq.dev:8443/135f94801b8e92a823d13d8f1292dbc4
 DEBUG consensus            | Syncing blockchain with peer ws://validator10.validators.devnet.nimiq.dev:8443/58f0ca64e378f11b1088fc11f0e5f9e1
 DEBUG consensus            | Finished sync with peer ws://validator10.validators.devnet.nimiq.dev:8443/58f0ca64e378f11b1088fc11f0e5f9e1
 DEBUG consensus            | Syncing blockchain with peer ws://validator9.validators.devnet.nimiq.dev:8443/b8da5b9beccdcea073d565193330fc6d
 DEBUG consensus            | Finished sync with peer ws://validator9.validators.devnet.nimiq.dev:8443/b8da5b9beccdcea073d565193330fc6d
 DEBUG consensus            | Syncing blockchain with peer ws://alba-dev.uberpool.club:8443/a59ea240f6a792bdec5d0d237f5120b9
 ERROR deadlock             | 1 deadlocks detected
 ERROR deadlock             | Deadlock #0
 ERROR deadlock             | Thread Id 139992745510656
 ERROR deadlock             |    0:     0x55fe4ced6b7d - backtrace::backtrace::libunwind::trace::hd49579e70af3996f
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
                           backtrace::backtrace::trace_unsynchronized::h10c4404e3dad141e
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   1:     0x55fe4ced6afe - backtrace::backtrace::trace::hc2d05875369e4674
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:53
   2:     0x55fe4cecbd0d - backtrace::capture::Backtrace::create::hcfb433e87918a2be
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:164
   3:     0x55fe4cecbc2d - backtrace::capture::Backtrace::new::h8cb1df901bb4f403
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/capture.rs:128
   4:     0x55fe4cdb15ba - parking_lot_core::parking_lot::deadlock_impl::on_unpark::h27e19b149f4598e7
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.6.2/src/parking_lot.rs:1140
   5:     0x55fe4cd8479b - parking_lot_core::parking_lot::deadlock::on_unpark::h91d2c93128ae06f5
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.6.2/src/parking_lot.rs:1073
   6:     0x55fe4cd8e25d - parking_lot_core::parking_lot::park::{{closure}}::h6eace4faf690a764
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.6.2/src/parking_lot.rs:591
   7:     0x55fe4cd8d029 - parking_lot_core::parking_lot::with_thread_data::h52a9976e97ef2419
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.6.2/src/parking_lot.rs:178
                           parking_lot_core::parking_lot::park::h197bfbcdfe23fc7c
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.6.2/src/parking_lot.rs:556
   8:     0x55fe4cd8946b - parking_lot::raw_mutex::RawMutex::lock_slow::h4d7f4dce5c346cd1
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.9.0/src/raw_mutex.rs:225
   9:     0x55fe4c209270 - <parking_lot::raw_mutex::RawMutex as lock_api::mutex::RawMutex>::lock::h92d0e99c5d15a531
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.9.0/src/raw_mutex.rs:51
  10:     0x55fe4c20f839 - lock_api::mutex::Mutex<R,T>::lock::h53417d33424ae9f5
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.4/src/mutex.rs:170
  11:     0x55fe4c1e7ad6 - <nimiq_blockchain_albatross::blockchain::Blockchain as nimiq_blockchain_base::AbstractBlockchain>::lock::h6be3699e86fc1398
                               at blockchain-albatross/src/blockchain.rs:1738
  12:     0x55fe4c0441ee - nimiq_mempool::Mempool<B>::push_transaction::hdd93ac36a380f60b
                               at /home/soeren/nimiq/core-rs-albatross/mempool/src/lib.rs:103
  13:     0x55fe4c1244e3 - nimiq_validator::validator::Validator::on_blockchain_event::h5f71f105abadf80b
                               at validator/src/validator.rs:294
  14:     0x55fe4c1727e2 - nimiq_validator::validator::Validator::init_listeners::{{closure}}::h2bdf5d7e931cd560
                               at validator/src/validator.rs:165
  15:     0x55fe4c17261e - <F as nimiq_utils::observer::Listener<E>>::on_event::hd12e81e40f310c29
                               at /home/soeren/nimiq/core-rs-albatross/utils/src/observer.rs:10
  16:     0x55fe4c21eb32 - nimiq_utils::observer::Notifier<E>::notify::hd47a80e4f6b05e2c
                               at /home/soeren/nimiq/core-rs-albatross/utils/src/observer.rs:48
  17:     0x55fe4c1dd897 - nimiq_blockchain_albatross::blockchain::Blockchain::extend::h5a807213cab37c25
                               at blockchain-albatross/src/blockchain.rs:758
  18:     0x55fe4c1db792 - nimiq_blockchain_albatross::blockchain::Blockchain::push_block::h7a344c23ef59303a
                               at blockchain-albatross/src/blockchain.rs:647
  19:     0x55fe4c1d7aed - nimiq_blockchain_albatross::blockchain::Blockchain::push::h1e99eb2351bc43a1
                               at blockchain-albatross/src/blockchain.rs:434
  20:     0x55fe4c1e79b1 - <nimiq_blockchain_albatross::blockchain::Blockchain as nimiq_blockchain_base::AbstractBlockchain>::push::h0c97ab0e4057c223
                               at blockchain-albatross/src/blockchain.rs:1711
  21:     0x55fe4bcab7e6 - nimiq_consensus::consensus_agent::sync::BlockQueue<B>::push_block::h1d23bdd74280ac4b
                               at /home/soeren/nimiq/core-rs-albatross/consensus/src/consensus_agent/sync.rs:426
  22:     0x55fe4bcacb4c - nimiq_consensus::consensus_agent::sync::BlockQueue<B>::push::hb93f1bc14d96f04f
                               at /home/soeren/nimiq/core-rs-albatross/consensus/src/consensus_agent/sync.rs:396
  23:     0x55fe4bcab347 - <nimiq_consensus::consensus_agent::sync::FullSync<B> as nimiq_consensus::consensus_agent::sync::SyncProtocol<B>>::on_block::h28b276f2435c160d
                               at /home/soeren/nimiq/core-rs-albatross/consensus/src/consensus_agent/sync.rs:86
  24:     0x55fe4bc73bab - nimiq_consensus::inventory::agent::InventoryAgent<P>::on_block::he3412ebf0de6516b
                               at /home/soeren/nimiq/core-rs-albatross/consensus/src/inventory/agent.rs:460
  25:     0x55fe4bc6d3bd - nimiq_consensus::inventory::agent::InventoryAgent<P>::init_listeners::{{closure}}::hf041e4b7f36a8429
                               at /home/soeren/nimiq/core-rs-albatross/consensus/src/inventory/agent.rs:243
  26:     0x55fe4b9a4556 - nimiq_utils::observer::weak_passthru_listener::{{closure}}::h6d7f421449300d7a
                               at /home/soeren/nimiq/core-rs-albatross/utils/src/observer.rs:67
  27:     0x55fe4b9a79dc - <F as nimiq_utils::observer::PassThroughListener<E>>::on_event::h28158aaa9c53ce0a
                               at /home/soeren/nimiq/core-rs-albatross/utils/src/observer.rs:79
  28:     0x55fe4c97a0e6 - nimiq_utils::observer::PassThroughNotifier<E>::notify::hbd42ca26ba8f4e28
                               at /home/soeren/nimiq/core-rs-albatross/utils/src/observer.rs:110
  29:     0x55fe4c960f9b - nimiq_messages::MessageNotifier::notify::h3e79a81309df2d93
                               at messages/src/lib.rs:608
  30:     0x55fe4c377676 - nimiq_network::peer_channel::channel::PeerChannel::new::{{closure}}::hb246504a1e826518
                               at network/src/peer_channel/channel.rs:68
  31:     0x55fe4c377492 - <F as nimiq_utils::observer::PassThroughListener<E>>::on_event::hdf7d1a3de8df2d29
                               at /home/soeren/nimiq/core-rs-albatross/utils/src/observer.rs:79
  32:     0x55fe4c31ca33 - nimiq_utils::observer::PassThroughNotifier<E>::notify::h3ce946cb1db6a58f
                               at /home/soeren/nimiq/core-rs-albatross/utils/src/observer.rs:110
  33:     0x55fe4c3c5da5 - nimiq_network::peer_channel::stream::PeerStream::process_stream::{{closure}}::h68d5042970ef21bb
                               at network/src/peer_channel/stream.rs:53
  34:     0x55fe4c37b1bb - <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::h292991b65656f3ce
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/stream/for_each.rs:46
  35:     0x55fe4c3a6922 - futures::future::chain::Chain<A,B,C>::poll::h27ef719541dae887
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
  36:     0x55fe4c366c16 - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h7315df671e0631e3
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32
  37:     0x55fe4c388803 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h9c76a70d5c072787
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/map_err.rs:30
  38:     0x55fe4c3614a9 - <futures::future::select::Select<A,B> as futures::future::Future>::poll::he2062868027dcd49
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/select.rs:52
  39:     0x55fe4c35ba28 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h11645bfad7da14db
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/map.rs:30
  40:     0x55fe4c388143 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h81ab09011c53099f
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/map_err.rs:30
  41:     0x55fe4c28b836 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hc421fd96c222c950
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  42:     0x55fe4c2ac5df - <nimiq_network::connection::network_connection::ProcessConnectionFuture as futures::future::Future>::poll::he1cd876d60386c51
                               at network/src/connection/network_connection.rs:157
  43:     0x55fe4cd7a916 - <alloc::boxed::Box<F> as futures::future::Future>::poll::h658e09de1c7adc98
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113
  44:     0x55fe4ccf8c4f - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h452719604c30225a
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  45:     0x55fe4ccf8f0f - futures::task_impl::Spawn<T>::enter::{{closure}}::hc2f2d0236335f17b
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  46:     0x55fe4cd04c5b - futures::task_impl::std::set::h7fba8ac0af5d2197
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83
  47:     0x55fe4ccf8d42 - futures::task_impl::Spawn<T>::enter::h3c3901ed723db5a9
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399
  48:     0x55fe4ccf8a58 - futures::task_impl::Spawn<T>::poll_fn_notify::h0ebefbcc5e5b879b
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291
  49:     0x55fe4ccf8bd9 - futures::task_impl::Spawn<T>::poll_future_notify::h7f3872d1c8b607bf
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329
  50:     0x55fe4ccfc43c - tokio_threadpool::task::Task::run::{{closure}}::hefbdc1f0ba513f27
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/task/mod.rs:145
  51:     0x55fe4cd1eaf9 - core::ops::function::FnOnce::call_once::h582e392d6044dd31
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  52:     0x55fe4ccf4949 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h395699d3d02a838f
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  53:     0x55fe4cd02ec5 - std::panicking::try::do_call::h473d454752eff783
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  54:     0x55fe4cd071ad - __rust_try
  55:     0x55fe4cd02c0a - std::panicking::try::h1afde4c8f1431257
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  56:     0x55fe4ccf4e31 - std::panic::catch_unwind::h4ab7b875e293e39d
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  57:     0x55fe4ccfbd9a - tokio_threadpool::task::Task::run::hb5e9f5b58679f698
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/task/mod.rs:130
  58:     0x55fe4cd0c4a6 - tokio_threadpool::worker::Worker::run_task2::h8fa75d3efc78f1f2
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:567
  59:     0x55fe4cd0bd79 - tokio_threadpool::worker::Worker::run_task::h34f6e2b217d2c6d8
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:459
  60:     0x55fe4cd0b898 - tokio_threadpool::worker::Worker::try_steal_task::h60460223ad8c46cd
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:416
  61:     0x55fe4cd0af1a - tokio_threadpool::worker::Worker::try_run_task::hdcf3ea887583d364
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:301
  62:     0x55fe4cd0ad4f - tokio_threadpool::worker::Worker::run::h88bd7fab9869322e
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:241
  63:     0x55fe4ccbb7e7 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hf2b43b3d59873fc9
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:390
  64:     0x55fe4ccb973c - tokio_timer::timer::handle::with_default::heee6f05a4b1ca581
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/timer/handle.rs:74
  65:     0x55fe4ccbb849 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h25f907992c63b0ff
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:382
  66:     0x55fe4ccb49dd - tokio_timer::clock::clock::with_default::h77ce5a58d74112cc
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/clock/clock.rs:125
  67:     0x55fe4ccbb885 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::hfd9a4182952fee96
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:381
  68:     0x55fe4ccb895d - tokio_reactor::with_default::hcf1d50a4334fce78
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.12/src/lib.rs:220
  69:     0x55fe4ccbb93c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::habbce4e505806557
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/builder.rs:380
  70:     0x55fe4ccfb3b7 - tokio_threadpool::callback::Callback::call::h9b87bf083455c85d
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/callback.rs:22
  71:     0x55fe4cd0aa11 - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::h0cf0d1e6689044c9
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:127
  72:     0x55fe4cd23309 - tokio_executor::global::with_default::{{closure}}::h7cd926fc0e1637ee
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:221
  73:     0x55fe4cd0e295 - std::thread::local::LocalKey<T>::try_with::h6c788189c063b7d2
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  74:     0x55fe4cd0dc6e - std::thread::local::LocalKey<T>::with::h9dc5674a356323b6
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  75:     0x55fe4cd231ee - tokio_executor::global::with_default::h6f143a6a28169190
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:190
  76:     0x55fe4cd0aacf - tokio_threadpool::worker::Worker::do_run::{{closure}}::hd0808e11a61096db
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:125
  77:     0x55fe4cd0ddbd - std::thread::local::LocalKey<T>::try_with::h32e9d347620bd221
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  78:     0x55fe4cd0db14 - std::thread::local::LocalKey<T>::with::h0828981a825aaed1
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  79:     0x55fe4cd0a8d5 - tokio_threadpool::worker::Worker::do_run::h36d71040f0478427
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/worker/mod.rs:116
  80:     0x55fe4cd147e8 - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::hc9733a2ca1bdcc2f
                               at /home/soeren/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.18/src/pool/mod.rs:345
  81:     0x55fe4cd0dac1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbeacbad56cde7ab2
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys_common/backtrace.rs:130
  82:     0x55fe4cd07d22 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h86a4645c4d2011c2
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:475
  83:     0x55fe4ccf4992 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h476be96cd5e6296c
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  84:     0x55fe4cd02e5c - std::panicking::try::do_call::h37e6c803b56857bd
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:297
  85:     0x55fe4cd071ad - __rust_try
  86:     0x55fe4cd02d83 - std::panicking::try::he1dac7bba8622f23
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:274
  87:     0x55fe4ccf4e72 - std::panic::catch_unwind::h7af104821e0635e3
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  88:     0x55fe4cd07b11 - std::thread::Builder::spawn_unchecked::{{closure}}::h602d8220544837f0
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/mod.rs:474
  89:     0x55fe4cd1e8bf - core::ops::function::FnOnce::call_once{{vtable.shim}}::h44f1699940150c61
                               at /home/soeren/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  90:     0x55fe4cf1e12a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h54527dd7ea0101d8
                               at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/liballoc/boxed.rs:1076
                           <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h731fd1bfc62ba945
                               at /rustc/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/liballoc/boxed.rs:1076
                           std::sys::unix::thread::Thread::new::thread_start::h62c1349f59256f0d
                               at src/libstd/sys/unix/thread.rs:87
  91:     0x7f529a3364e2 - start_thread
  92:     0x7f529a2496a3 - clone
  93:                0x0 - <unknown>

 DEBUG connection_pool      | Connection to ws://validator4.validators.devnet.nimiq.dev:8443/59c3541838a88fa50288b0506db611b2 failed with error Connection timed out
 DEBUG connection_pool      | Connection to ws://seed2.validators.devnet.nimiq.dev:8443/ca29825adf54ca7e0c721883c9bff7d0 failed with error Connection timed out
 DEBUG connection_pool      | Connection to ws://77.179.173.26:8443/60f2d8c8262a0fb47c301482a8f49816 failed with error Connection timed out
 DEBUG sink                 | Closing connection, reason: GetBlocksTimeout (None)
```

**Comment by maestroi** [comment]
had the same problem on master, with the fix it didn't happend again yet, but i could test when devent is restarted :)
