### ISSUE TITLE
2 panics observed in `Tree`

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#1587]
Tag 0.11.3 with Full client

[Panic in Trie.log](https://github.com/nimiq/core-rs-albatross/files/11389948/Panic.in.Trie.log)

It started with a bunch of

```
2023-05-03T18:48:16.357421000Z ERROR trie                 | Putting chunk failed, have hash a4f5c5324e697e0feb531900918b4125c2c6f7d02be3888bdb1c47a71a30c2e2 wanted hash e32b85ebc8d5ea6ddce758955a38ff2ecd141e40a05771b8e4cae667bc7f1e1f
2023-05-03T18:48:16.357495000Z WARN  push                 | Commit chunk for block 06774507dd7a42938291cf5932250875eacffb6973470d793bd11bb0eb52775d failed: Error during chunk processing: Root hash does not match expected hash after applying chunk.
2023-05-03T18:48:16.383457000Z ERROR trie                 | Putting chunk failed, have hash a4f5c5324e697e0feb531900918b4125c2c6f7d02be3888bdb1c47a71a30c2e2 wanted hash e32b85ebc8d5ea6ddce758955a38ff2ecd141e40a05771b8e4cae667bc7f1e1f
2023-05-03T18:48:16.383536000Z WARN  push                 | Commit chunk for block 06774507dd7a42938291cf5932250875eacffb6973470d793bd11bb0eb52775d failed: Error during chunk processing: Root hash does not match expected hash after applying chunk.
2023-05-03T18:48:16.584667000Z ERROR trie                 | Putting chunk failed, have hash a4f5c5324e697e0feb531900918b4125c2c6f7d02be3888bdb1c47a71a30c2e2 wanted hash e32b85ebc8d5ea6ddce758955a38ff2ecd141e40a05771b8e4cae667bc7f1e1f
2023-05-03T18:48:16.584768000Z WARN  push                 | Commit chunk for block 06774507dd7a42938291cf5932250875eacffb6973470d793bd11bb0eb52775d failed: Error during chunk processing: Root hash does not match expected hash after applying chunk.
2023-05-03T18:48:16.596694000Z DEBUG handler              | Inbound and outbound connected. Performing handshake
2023-05-03T18:48:16.613887000Z ERROR trie                 | Putting chunk failed, have hash a4f5c5324e697e0feb531900918b4125c2c6f7d02be3888bdb1c47a71a30c2e2 wanted hash e32b85ebc8d5ea6ddce758955a38ff2ecd141e40a05771b8e4cae667bc7f1e1f
2023-05-03T18:48:16.614008000Z WARN  push                 | Commit chunk for block 06774507dd7a42938291cf5932250875eacffb6973470d793bd11bb0eb52775d failed: Error during chunk processing: Root hash does not match expected hash after applying chunk.
2023-05-03T18:48:16.816754000Z ERROR trie                 | Putting chunk failed, have hash a4f5c5324e697e0feb531900918b4125c2c6f7d02be3888bdb1c47a71a30c2e2 wanted hash e32b85ebc8d5ea6ddce758955a38ff2ecd141e40a05771b8e4cae667bc7f1e1f
2023-05-03T18:48:16.816842000Z WARN  push                 | Commit chunk for block 06774507dd7a42938291cf5932250875eacffb6973470d793bd11bb0eb52775d failed: Error during chunk processing: Root hash does not match expected hash after applying chunk.
2023-05-03T18:48:16.856932000Z ERROR trie                 | Putting chunk failed, have hash a4f5c5324e697e0feb531900918b4125c2c6f7d02be3888bdb1c47a71a30c2e2 wanted hash e32b85ebc8d5ea6ddce758955a38ff2ecd141e40a05771b8e4cae667bc7f1e1f
2023-05-03T18:48:16.857015000Z WARN  push                 | Commit chunk for block 06774507dd7a42938291cf5932250875eacffb6973470d793bd11bb0eb52775d failed: Error during chunk processing: Root hash does not match expected hash after applying chunk.
```
and eventually paniced with

```
2023-05-03T18:49:14.889002000Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Tree must be complete: IncompleteTrie': primitives/account/src/accounts.rs:76
   0: backtrace::capture::Backtrace::new
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: nimiq_blockchain::blockchain::inherents::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::create_reward_transactions
   9: nimiq_blockchain::blockchain::verify::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::verify_block_state
  10: nimiq_blockchain::blockchain::push::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::check_and_commit
  11: nimiq_blockchain::blockchain::push::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::extend
  12: nimiq_blockchain::blockchain::push::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::push_wrapperfn
  13: nimiq_consensus::sync::live::queue::blockchain_push
  14: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  15: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  16: tokio::runtime::task::core::Core<T,S>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::blocking::pool::Inner::run
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
  21: std::sys::unix::thread::Thread::new::thread_start
  22: __pthread_joiner_wake
    
2023-05-03T18:49:14.889444000Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'blockchain.push() should not panic: JoinError::Panic(Id(428), ...)': /Users/stefan/code/nimiq/core-rs-albatross/consensus/src/sync/live/queue.rs:197
   0: backtrace::capture::Backtrace::new
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: nimiq_consensus::sync::live::queue::push_block_and_chunks::{{closure}}
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  10: futures_util::stream::stream::StreamExt::poll_next_unpin
  11: futures_util::stream::stream::StreamExt::poll_next_unpin
  12: <nimiq_consensus::consensus::Consensus<N> as core::future::future::Future>::poll
  13: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  18: tokio::runtime::scheduler::multi_thread::worker::Context::run
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
  20: tokio::runtime::scheduler::multi_thread::worker::run
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  22: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: std::sys::unix::thread::Thread::new::thread_start
  28: __pthread_joiner_wake
    
```

**Comment by Eligioo** [comment]
Another observation but this time with TRACE enabled

[Panic in tree.log](https://github.com/nimiq/core-rs-albatross/files/11422394/Panic.in.tree.log)
