### ISSUE TITLE
Panic while creating proposal

### ISSUE THREAD

**Issue by styppo** [nimiq/core-rs-albatross#1980]
A panic was observed in [this CI Run](https://github.com/nimiq/core-rs-albatross/actions/runs/6910209300).
```
2023-11-18T00:24:26.535524539Z DEBUG push                 | Accepted block block=#959:MI:69e888bda9 num_transactions=100 kind="extend"
2023-11-18T00:24:26.535863490Z TRACE validator            | blockchain event event=Extended(69e888bda9cfbc796f1ada05d5b38bc463cb345606c04ff9524741c4c3118e6f) can_be_active=true
2023-11-18T00:24:26.556407994Z DEBUG block_queue          | Received block via gossipsub block=#960:MA:1d91b2030e peer_id=12D3KooWJjMcEuTaqBqaFW65cxy9ySQPaDHy13yX7P2E6sSHYwEn
2023-11-18T00:24:26.568410789Z DEBUG validator            | Initializing block producer next_block_number=960
2023-11-18T00:24:26.834394233Z DEBUG reward               | Computed the batch delay and penalty (if any) block_number=960 delay=63440 penalty=0.5059745640835149
2023-11-18T00:24:26.858373034Z DEBUG push                 | Accepted block block=#960:MA:1d91b2030e num_transactions=0 kind="extend"
2023-11-18T00:24:26.876785185Z DEBUG block_queue          | Received block via gossipsub block=#961:MI:5bf7bbdd01 peer_id=12D3KooWL6djG78iqaPQTnMeuvSCSsN4nmGS1izGi16BcK1boSZg
2023-11-18T00:24:26.890603683Z DEBUG verify               | Tendermint - await_proposal: Invalid block header for blockchain macro head error=Invalid block number block=#960:MA:1d91b2030e
2023-11-18T00:24:26.890998147Z DEBUG tendermint           | Proposal verification failed error=InvalidBlock(InvalidBlockNumber) proposal=SignedProposalMessage { message: ProposalMessage { round: 2, valid_round: None, proposal: Header(MacroHeader { version: 1, block_number: 960, round: 2, timestamp: 1700267042404, parent_hash: 69e888bda9cfbc796f1ada05d5b38bc463cb345606c04ff9524741c4c3118e6f, parent_election_hash: e17aed9506e2b18722a92c8860446ad5faaaee964915f622881387a3a4de90ae, interlink: None, seed: VrfSeed("0abd7b0c739ddbd150a79dcabe22e9e6132c7b08c646e835ee9eaffed06628bd61eb7392434dc8a05c051f54ae7ee8246506924e17074f83a54c6329792152012cb3a81e3eb8178048033cd9326ed829b898fe3f81e7fd5d0d122a1b2e09e20c"), extra_data: [], state_root: 44e06e4834eaeaf65a98491261cc7e032d5385c820fa62cae5c12b8cb2943e13, body_root: ceb42683d72387a9ab108d6648fa61171fe9b9a660875714d5c84fb60706013f, diff_root: e804a4cde5510943a85a3d89fe7f1205d8d4b2467c7552fdbb8311cc9d23dea3, history_root: 69533d1f28eff301f9c3d95283b87f270983b9162cda3ebea76ab7f0bbc3c81f }, Some(GossipsubId { message_id: MessageId(3137383031363238303835373034343631303837), propagation_source: PeerId("12D3KooWLhKX33J5KDb66hmFmaKCBExot1JfASQmmtStZoQKDHhU") })) }, signature: (Signature(ed25519::Signature { R: [1, 225, 149, 42, 27, 35, 90, 108, 37, 107, 68, 125, 135, 242, 58, 168, 9, 200, 127, 76, 52, 56, 89, 53, 18, 157, 171, 70, 131, 247, 37, 23], s: [237, 80, 110, 162, 161, 10, 191, 139, 192, 153, 15, 247, 137, 15, 134, 196, 200, 218, 70, 162, 151, 134, 183, 193, 143, 223, 158, 68, 159, 143, 142, 1] }), 2) }
2023-11-18T00:24:26.895036711Z DEBUG tendermint           | Proposal did not verify error=InvalidProposal proposal.message=ProposalMessage { round: 2, valid_round: None, proposal: Header(MacroHeader { version: 1, block_number: 960, round: 2, timestamp: 1700267042404, parent_hash: 69e888bda9cfbc796f1ada05d5b38bc463cb345606c04ff9524741c4c3118e6f, parent_election_hash: e17aed9506e2b18722a92c8860446ad5faaaee964915f622881387a3a4de90ae, interlink: None, seed: VrfSeed("0abd7b0c739ddbd150a79dcabe22e9e6132c7b08c646e835ee9eaffed06628bd61eb7392434dc8a05c051f54ae7ee8246506924e17074f83a54c6329792152012cb3a81e3eb8178048033cd9326ed829b898fe3f81e7fd5d0d122a1b2e09e20c"), extra_data: [], state_root: 44e06e4834eaeaf65a98491261cc7e032d5385c820fa62cae5c12b8cb2943e13, body_root: ceb42683d72387a9ab108d6648fa61171fe9b9a660875714d5c84fb60706013f, diff_root: e804a4cde5510943a85a3d89fe7f1205d8d4b2467c7552fdbb8311cc9d23dea3, history_root: 69533d1f28eff301f9c3d95283b87f270983b9162cda3ebea76ab7f0bbc3c81f }, Some(GossipsubId { message_id: MessageId(3137383031363238303835373034343631303837), propagation_source: PeerId("12D3KooWLhKX33J5KDb66hmFmaKCBExot1JfASQmmtStZoQKDHhU") })) }
2023-11-18T00:24:26.910963762Z DEBUG propose              | Our turn, setting fresh proposal current_round=0
2023-11-18T00:24:30.482114746Z ERROR log                  | thread 'tokio-runtime-worker' panicked at 'assertion failed: Policy::is_macro_block_at(block_number)': primitives/account/src/account/staking_contract/punished_slots.rs:222
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.67/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:735:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:601:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   6: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   7: core::panicking::panic
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
   8: nimiq_account::account::staking_contract::punished_slots::PunishedSlots::finalize_batch
             at primitives/account/src/account/staking_contract/punished_slots.rs:222:13
   9: nimiq_account::account::staking_contract::punished_slots::PunishedSlots::next_batch_initial_punished_set
             at primitives/account/src/account/staking_contract/punished_slots.rs:241:9
  10: nimiq_blockchain::block_production::BlockProducer::next_macro_body
             at blockchain/src/block_production/mod.rs:336:47
  11: nimiq_blockchain::block_production::BlockProducer::next_macro_block_proposal_with_rng
             at blockchain/src/block_production/mod.rs:278:20
  12: nimiq_blockchain::block_production::BlockProducer::next_macro_block_proposal
             at blockchain/src/block_production/mod.rs:206:9
  13: <nimiq_validator::tendermint::TendermintProtocol<TValidatorNetwork> as nimiq_tendermint::protocol::Protocol>::create_proposal
             at validator/src/tendermint.rs:228:21
  14: nimiq_tendermint::states::propose::<impl nimiq_tendermint::tendermint::Tendermint<TProtocol>>::propose
             at tendermint/src/states/propose.rs:136:39
  15: <nimiq_tendermint::tendermint::Tendermint<TProtocol> as futures_core::stream::Stream>::poll_next
             at tendermint/src/tendermint.rs:646:21
  16: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.29/src/stream/stream/map.rs:58:26
  17: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.29/src/stream.rs:120:9
  18: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.29/src/stream/stream/mod.rs:1638:9
  19: <nimiq_validator::macro::ProduceMacroBlock<TValidatorNetwork> as futures_core::stream::Stream>::poll_next
             at validator/src/macro.rs:146:9
  20: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.29/src/stream/stream/mod.rs:1638:9
  21: nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork>::poll_macro
             at validator/src/validator.rs:549:46
  22: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
             at validator/src/validator.rs:859:17
```

**Comment by nibhar** [comment]
Tentatively fixed by 953430ae2b61934b58585d04a6a3c282c6d3d265
