### ISSUE TITLE
Panic: we should always have the staking contract

### ISSUE THREAD

**Issue by redmaner** [nimiq/core-rs-albatross#2081]
### General information

- Library version(s): v0.18.0
- Reproducible in the testnet? (Yes/No):  yes

## Bug report
Running a full node on testnet using the latest tag. When trying to send a `reactivate validator transaction`  for an inactive validator the RPC server panics with the below message:
```
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]: 2023-12-29T10:29:17.025602165Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'We should always have the staking contract.': blockchain/src/blockchain/wrappers.rs:127
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    1: log_panics::Config::install_panic_hook::{{closure}}
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:       std::panicking::rust_panic_with_hook
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    3: std::panicking::begin_panic_handler::{{closure}}
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    5: rust_begin_unwind
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    6: core::panicking::panic_fmt
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    7: core::panicking::panic_display
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:168:5
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:       core::panicking::panic_str
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:152:5
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:       core::option::expect_failed
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/option.rs:1988:5
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    8: nimiq_blockchain::blockchain::wrappers::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::get_staking_contract
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:    9: <nimiq_rpc_server::dispatchers::consensus::ConsensusDispatcher as nimiq_rpc_interface::consensus::ConsensusInterface>::send_reactivate_validator_transaction::{{closure}}
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   10: <nimiq_rpc_server::dispatchers::consensus::ConsensusDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   11: <nimiq_jsonrpc_server::ModularDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   12: <nimiq_jsonrpc_server::AllowListDispatcher<D> as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   13: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   14: <warp::filter::recover::RecoverFuture<T,F> as core::future::future::Future>::poll
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   15: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   16: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   17: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   18: tokio::runtime::task::core::Core<T,S>::poll
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   19: tokio::runtime::task::harness::Harness<T,S>::poll
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   20: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   21: tokio::runtime::scheduler::multi_thread::worker::Context::run
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   22: tokio::runtime::context::scoped::Scoped<T>::set
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   23: tokio::runtime::context::runtime::enter_runtime
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   24: tokio::runtime::scheduler::multi_thread::worker::run
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   25: tokio::runtime::task::core::Core<T,S>::poll
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   26: tokio::runtime::task::harness::Harness<T,S>::poll
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   27: tokio::runtime::blocking::pool::Inner::run
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   28: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   29: core::ops::function::FnOnce::call_once{{vtable.shim}}
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:       std::sys::unix::thread::Thread::new::thread_start
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:              at rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   31: <unknown>
Dec 29 10:29:17 vps-a60b17b1 nimiq-client[96657]:   32: <unknown>
```

I also see a lot of the below messages:
```
Dec 29 10:28:58 vps-a60b17b1 nimiq-client[96657]: 2023-12-29T10:28:58.893839260Z WARN  wrappers             | Could not get account for address address=NQ62 JE6M Q130 MF10 M92K HQRR P394 L8MK HE7R

```
The account address is not always the same. The node does have consensus and seems to be fully in sync with the chain. Restarting the node seems to resolve the issue.

**Comment by sisou** [comment]
I am observing the same state regularly (at least once every 48 hours) in my validator full node. In this state, the validator cannot produce blocks and does not reactivate itself. I found a good test for this state is to query the validator via RPC `getValidatorByAddress` and if it returns "internal error: no consensus", restart the node. RPC reports consensus established, but an outdated head block via their methods in this state.

**Comment by redmaner** [comment]
This is not on a validator node though. Just a regular full node in the network I use to interact with the network. Basically sending transactions and retrieving state. Not sure if that is relevant for this bug.

**Comment by sisou** [comment]
I think it's not relevant. You can still query any validator via RPC from that node.
