### ISSUE TITLE
Validator panics calculating reward: "current_timestamp >= previous_timestamp"

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#233]
## Bug report

Seed 1 validator got dropped successfully (failing to reproduce #232), then it got recreated as a new validator. After a short while, but after already producing micro blocks, it panics.

### Sequence

1. Seed1 validator got retired at election block 256
2. Seed1 validator got dropped at next opportunity, but seed1 stayed connected and with consensus established
3. Seed1 validator got recreated (with new validator ID) in election block 768 and successfully started producing micro blocks
4. Seed1 rejects a block (possibly a macroblock proposal?), claiming "wrong parent election hash", but also outputs "Consensus established: true - Head 799
5. Macroblock 800 gets published
6. Seed1 continues successfully creating micro blocks
7. Seed1 produces micro block 863 (last micro block of seed1)
8. Seed4 produces micro block 874
9. Seed1 panics (see crash log)
10. The other seeds trigger view changes and continue the chain without seed1

#### Steps to reproduce

See sequence above. Could not be reproduced during the next run.

#### Crash log

```
seed4_1    |  2021-03-17 08:45:00 INFO  micro                | [2] Our turn at #874:0, producing micro block
seed4_1    |  2021-03-17 08:45:00 INFO  behaviour            | Published message: MessageId(313244334b6f6f574d4e34794d6f4a684c7951354356665066395379424a547656655238754542706f726261557744664d5a727a36383636363535333833303336333532323437)
seed1_1    |  2021-03-17 08:45:00 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'assertion failed: current_timestamp >= previous_timestamp': blockchain-albatross/src/reward.rs:41
seed1_1    |    0: log_panics::init::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
seed1_1    |    1: std::panicking::rust_panic_with_hook
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:595:17
seed1_1    |    2: std::panicking::begin_panic_handler::{{closure}}
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:495:13
seed1_1    |    3: std::sys_common::backtrace::__rust_end_short_backtrace
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/sys_common/backtrace.rs:141:18
seed1_1    |    4: rust_begin_unwind
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:493:5
seed1_1    |    5: core::panicking::panic_fmt
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/panicking.rs:92:14
seed1_1    |    6: core::panicking::panic
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/panicking.rs:50:5
seed1_1    |    7: nimiq_blockchain_albatross::reward::block_reward_for_batch
seed1_1    |              at /build/blockchain-albatross/src/reward.rs:41:5
seed1_1    |    8: nimiq_blockchain_albatross::blockchain::inherents::<impl nimiq_blockchain_albatross::blockchain::blockchain::Blockchain>::finalize_previous_batch
seed1_1    |              at /build/blockchain-albatross/src/blockchain/inherents.rs:154:28
seed1_1    |    9: nimiq_blockchain_albatross::blockchain::accounts::<impl nimiq_blockchain_albatross::blockchain::blockchain::Blockchain>::commit_accounts
seed1_1    |              at /build/blockchain-albatross/src/blockchain/accounts.rs:31:39
seed1_1    |   10: <nimiq_validator::tendermint_outside_deps::TendermintInterface<N> as nimiq_tendermint::outside_deps::TendermintOutsideDeps>::await_proposal::{{closure}}
seed1_1    |              at /build/validator/src/tendermint_outside_deps.rs:278:12
seed1_1    |   11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/future/mod.rs:80:19
seed1_1    |   12: <core::pin::Pin<P> as core::future::future::Future>::poll
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/future/future.rs:119:9
seed1_1    |   13: nimiq_tendermint::network::<impl nimiq_tendermint::tendermint::Tendermint<ProposalTy,ProofTy,ResultTy,DepsTy>>::await_proposal::{{closure}}
seed1_1    |              at /build/tendermint/src/network.rs:23:28
seed1_1    |   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/future/mod.rs:80:19
seed1_1    |   15: nimiq_tendermint::protocol::<impl nimiq_tendermint::tendermint::Tendermint<ProposalTy,ProofTy,ResultTy,DepsTy>>::start_round::{{closure}}
seed1_1    |              at /build/tendermint/src/protocol.rs:63:13
seed1_1    |   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/future/mod.rs:80:19
seed1_1    |   17: nimiq_tendermint::stream::expect_block::{{closure}}
seed1_1    |              at /build/tendermint/src/stream.rs:55:39
seed1_1    |   18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/future/mod.rs:80:19
seed1_1    |   19: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.0/src/async_stream.rs:53:17
seed1_1    |   20: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/stream.rs:129:9
seed1_1    |   21: futures_util::stream::stream::StreamExt::poll_next_unpin
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/mod.rs:1415:9
seed1_1    |   22: <nimiq_validator::macro::ProduceMacroBlock as futures_core::stream::Stream>::poll_next
seed1_1    |              at /build/validator/src/macro.rs:124:9
seed1_1    |   23: futures_util::stream::stream::StreamExt::poll_next_unpin
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/stream/stream/mod.rs:1415:9
seed1_1    |   24: nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork>::poll_macro
seed1_1    |              at /build/validator/src/validator.rs:334:46
seed1_1    |   25: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
seed1_1    |              at /build/validator/src/validator.rs:486:17
seed1_1    |   26: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
seed1_1    |   27: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
seed1_1    |   28: tokio::runtime::task::core::Core<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
seed1_1    |   29: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
seed1_1    |   30: core::ops::function::FnOnce::call_once
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/ops/function.rs:227:5
seed1_1    |   31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panic.rs:344:9
seed1_1    |   32: std::panicking::try::do_call
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:379:40
seed1_1    |   33: __rust_try
seed1_1    |   34: std::panicking::try
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:343:19
seed1_1    |   35: std::panic::catch_unwind
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panic.rs:431:14
seed1_1    |   36: tokio::runtime::task::harness::Harness<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
seed1_1    |   37: tokio::runtime::task::raw::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
seed1_1    |   38: tokio::runtime::task::raw::RawTask::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
seed1_1    |   39: tokio::runtime::task::Notified<S>::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
seed1_1    |   40: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:349:13
seed1_1    |   41: tokio::coop::with_budget::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
seed1_1    |   42: std::thread::local::LocalKey<T>::try_with
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/thread/local.rs:272:16
seed1_1    |   43: std::thread::local::LocalKey<T>::with
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/thread/local.rs:248:9
seed1_1    |   44: tokio::coop::with_budget
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
seed1_1    |       tokio::coop::budget
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
seed1_1    |       tokio::runtime::thread_pool::worker::Context::run_task
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:348:9
seed1_1    |   45: tokio::runtime::thread_pool::worker::Context::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:320:24
seed1_1    |   46: tokio::runtime::thread_pool::worker::run::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:305:17
seed1_1    |   47: tokio::macros::scoped_tls::ScopedKey<T>::set
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
seed1_1    |   48: tokio::runtime::thread_pool::worker::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:302:5
seed1_1    |   49: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:281:45
seed1_1    |   50: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
seed1_1    |   51: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
seed1_1    |   52: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
seed1_1    |   53: tokio::runtime::task::core::Core<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
seed1_1    |   54: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
seed1_1    |   55: core::ops::function::FnOnce::call_once
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/ops/function.rs:227:5
seed1_1    |   56: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panic.rs:344:9
seed1_1    |   57: std::panicking::try::do_call
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:379:40
seed1_1    |   58: __rust_try
seed1_1    |   59: std::panicking::try
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:343:19
seed1_1    |   60: std::panic::catch_unwind
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panic.rs:431:14
seed1_1    |   61: tokio::runtime::task::harness::Harness<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
seed1_1    |   62: tokio::runtime::task::raw::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
seed1_1    |   63: tokio::runtime::task::raw::RawTask::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
seed1_1    |   64: tokio::runtime::task::Notified<S>::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
seed1_1    |   65: tokio::runtime::blocking::pool::Inner::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
seed1_1    |   66: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
seed1_1    |   67: tokio::runtime::context::enter
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
seed1_1    |   68: tokio::runtime::handle::Handle::enter
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
seed1_1    |   69: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17
seed1_1    |   70: std::sys_common::backtrace::__rust_begin_short_backtrace
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/sys_common/backtrace.rs:125:18
seed1_1    |   71: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/thread/mod.rs:474:17
seed1_1    |   72: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panic.rs:344:9
seed1_1    |   73: std::panicking::try::do_call
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:379:40
seed1_1    |   74: __rust_try
seed1_1    |   75: std::panicking::try
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panicking.rs:343:19
seed1_1    |   76: std::panic::catch_unwind
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/panic.rs:431:14
seed1_1    |   77: std::thread::Builder::spawn_unchecked::{{closure}}
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/thread/mod.rs:473:30
seed1_1    |   78: core::ops::function::FnOnce::call_once{{vtable.shim}}
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/core/src/ops/function.rs:227:5
seed1_1    |   79: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/alloc/src/boxed.rs:1546:9
seed1_1    |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/alloc/src/boxed.rs:1546:9
seed1_1    |       std::sys::unix::thread::Thread::new::thread_start
seed1_1    |              at /rustc/107896c32d5dda4db508968ff34997a39d286966/library/std/src/sys/unix/thread.rs:71:17
seed1_1    |   80: start_thread
seed1_1    |   81: clone
```

**Comment by nibhar** [comment]
Now tracked in #269 as the same error is referenced there as well.
