### ISSUE TITLE
Panic in validator-network: cache state must exist

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2546]
While testing the light history store, using the devnet script with:

- 4 validators as full nodes
- spammer as history node
- seed as history node

One of the validators encountered the following panic:

```
2024-05-29T21:46:28.886732000Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: cache state must exist': /Users/claudioviquez/Workspace/core-rs-albatross/validator-network/src/network_impl.rs:159
   0: backtrace::capture::Backtrace::new
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: nimiq_validator_network::network_impl::ValidatorNetworkImpl<N>::get_validator_cache::{{closure}}
   8: tokio::runtime::task::core::Core<T,S>::poll
   9: tokio::runtime::task::harness::Harness<T,S>::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::context::runtime::enter_runtime
  14: tokio::runtime::scheduler::multi_thread::worker::run
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::harness::Harness<T,S>::poll
  17: tokio::runtime::blocking::pool::Inner::run
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
  20: std::sys::unix::thread::Thread::new::thread_start
  21: __pthread_joiner_wake
```

**Comment by viquezclaudio** [comment]
This happened in validator 3, after validator 5 is killed by the script.
This is the sequence of events:


```
~/Workspace/core-rs-albatross$ python3 scripts/devnet/devnet.py -t .github/devnet_topologies/five_validators_spammer_full_nodes.toml -R -dt 60
2024-05-29 15:41:50 INFO     Generated genesis file in /Users/claudioviquez/Workspace/core-rs-albatross/temp-logs/20240529_154140/conf/dev-albatross.toml
2024-05-29 15:41:50 INFO     Building spammer1
2024-05-29 15:41:51 INFO     Building seed1
2024-05-29 15:41:51 INFO     Building validator1
2024-05-29 15:41:52 INFO     Building validator2
2024-05-29 15:41:53 INFO     Building validator3
2024-05-29 15:41:54 INFO     Building validator4
2024-05-29 15:41:55 INFO     Building validator5
2024-05-29 15:41:56 INFO     Starting seed1
2024-05-29 15:41:59 INFO     Starting spammer1
2024-05-29 15:42:00 INFO     Starting validator1
2024-05-29 15:42:01 INFO     Starting validator2
2024-05-29 15:42:02 INFO     Starting validator3
2024-05-29 15:42:03 INFO     Starting validator4
2024-05-29 15:42:04 INFO     Starting validator5
2024-05-29 15:43:05 INFO     Killing validator3
2024-05-29 15:43:07 INFO     Running with node(s) down for 60s
2024-05-29 15:44:09 INFO     Latest block number: 160
2024-05-29 15:44:09 INFO     Restarting validator3
2024-05-29 15:44:11 INFO     Producing blocks for 100s with all nodes up
2024-05-29 15:45:57 INFO     Latest block number: 269
2024-05-29 15:45:57 INFO     Killing validator5
2024-05-29 15:45:59 INFO     Running with node(s) down for 60s
2024-05-29 15:46:28 INFO     Killing all nodes
Traceback (most recent call last):
  File "/Users/claudioviquez/Workspace/core-rs-albatross/scripts/devnet/devnet.py", line 168, in <module>
    main()
  File "/Users/claudioviquez/Workspace/core-rs-albatross/scripts/devnet/devnet.py", line 161, in main
    topology.run(control_settings)
  File "/Users/claudioviquez/Workspace/core-rs-albatross/scripts/devnet/topology.py", line 504, in run
    self.__run_monitor_for(
  File "/Users/claudioviquez/Workspace/core-rs-albatross/scripts/devnet/topology.py", line 365, in __run_monitor_for
    raise Exception(
Exception: Panic found in nodes: ['validator3']
```

In summary:

- Validator 3 is killed and restarted
- Validators 3 syncs to the network (validity sync + state sync) everything normal
- Network runs for 100s without issues
- Validator 5 is killed 
- Panic in validator 3

**Comment by viquezclaudio** [comment]
Full logs:
[20240529_154140.zip](https://github.com/nimiq/core-rs-albatross/files/15491200/20240529_154140.zip)

**Comment by viquezclaudio** [comment]
As a note: 
Some policy constants were tweaked as part of the exercise:

```
        Policy {
            blocks_per_batch: 60,
            batches_per_epoch: 5,
            tendermint_timeout_init: 1000,
            tendermint_timeout_delta: 1000,
            state_chunks_max_size: 200, // #Nodes/accounts 200, TODO: Simulate with different sizes
            transaction_validity_window: 2,
            genesis_block_number: 0,
        }
```
