### ISSUE TITLE
Panic RPC getBatchInherents: thread 'tokio-runtime-worker' panicked at internal error: entered unreachable code

### ISSUE THREAD

**Issue by redmaner** [nimiq/core-rs-albatross#266]
### General information

- Library version(s): core-rs-albatross on latest lab-test branch
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): 
- Related issues:

#### Expected behavior
Calling the RPC method getBatchInherents returns a result. If no inherents are present for the particular batch, and empty array is returned.

I stumbled on this error consistently by accident. Our pool code was using the getBatchInherents method to get the batch rewards. Was switching the code over to use the getTransactionsByBlock instead since rewards are now changed to macro block transactions.

#### Actual behavior
The node crashes when calling getBatchInherents. See panic log pulled from docker-compose below.

#### Crash log pulled from docker logs
```
seed1_1    |  2021-05-12 08:10:05 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code': blockchain-albatross/src/history_store/extended_transaction.rs:96
seed1_1    |    0: log_panics::init::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
seed1_1    |    1: std::panicking::rust_panic_with_hook
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:595:17
seed1_1    |    2: std::panicking::begin_panic_handler::{{closure}}
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:495:13
seed1_1    |    3: std::sys_common::backtrace::__rust_end_short_backtrace
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/sys_common/backtrace.rs:141:18
seed1_1    |    4: rust_begin_unwind
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:493:5
seed1_1    |    5: core::panicking::panic_fmt
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/panicking.rs:92:14
seed1_1    |    6: core::panicking::panic
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/panicking.rs:50:5
seed1_1    |    7: nimiq_blockchain_albatross::history_store::extended_transaction::ExtendedTransaction::unwrap_inherent
seed1_1    |              at /build/blockchain-albatross/src/history_store/extended_transaction.rs:96:13
seed1_1    |    8: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_rpc_interface::blockchain::BlockchainInterface>::get_batch_inherents::{{closure}}::{{closure}}
seed1_1    |              at /build/rpc-server/src/dispatchers/blockchain.rs:239:21
seed1_1    |    9: core::iter::adapters::map::map_fold::{{closure}}
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/iter/adapters/map.rs:82:28
seed1_1    |   10: core::iter::traits::iterator::Iterator::fold
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/iter/traits/iterator.rs:2135:21
seed1_1    |   11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/iter/adapters/map.rs:122:9
seed1_1    |   12: core::iter::traits::iterator::Iterator::for_each
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/iter/traits/iterator.rs:776:9
seed1_1    |   13: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/alloc/src/vec/spec_extend.rs:42:17
seed1_1    |   14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
seed1_1    |   15: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/alloc/src/vec/source_iter_marker.rs:41:20
seed1_1    |   16: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/alloc/src/vec/mod.rs:2406:9
seed1_1    |   17: core::iter::traits::iterator::Iterator::collect
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/iter/traits/iterator.rs:1776:9
seed1_1    |   18: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_rpc_interface::blockchain::BlockchainInterface>::get_batch_inherents::{{closure}}
seed1_1    |              at /build/rpc-server/src/dispatchers/blockchain.rs:233:12
seed1_1    |   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   20: <core::pin::Pin<P> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/future.rs:120:9
seed1_1    |   21: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}::{{closure}}::{{closure}}
seed1_1    |              at /build/rpc-server/src/dispatchers/blockchain.rs:28:1
seed1_1    |   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   23: nimiq_jsonrpc_server::dispatch_method_with_args::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:479:18
seed1_1    |   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   25: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
seed1_1    |              at /build/rpc-server/src/dispatchers/blockchain.rs:28:1
seed1_1    |   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   27: <core::pin::Pin<P> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/future.rs:120:9
seed1_1    |   28: <nimiq_jsonrpc_server::ModularDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:360:24
seed1_1    |   29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   30: <core::pin::Pin<P> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/future.rs:120:9
seed1_1    |   31: <nimiq_jsonrpc_server::AllowListDispatcher<D> as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:422:13
seed1_1    |   32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   33: <core::pin::Pin<P> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/future.rs:120:9
seed1_1    |   34: nimiq_jsonrpc_server::Server<D>::handle_single_request::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:306:24
seed1_1    |   35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   36: nimiq_jsonrpc_server::Server<D>::handle_request::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:276:17
seed1_1    |   37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   38: nimiq_jsonrpc_server::Server<D>::handle_raw_request::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:253:28
seed1_1    |   39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   40: nimiq_jsonrpc_server::Server<D>::run::{{closure}}::{{closure}}::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:156:32
seed1_1    |   41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/future/mod.rs:80:19
seed1_1    |   42: <F as futures_core::future::TryFuture>::try_poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.15/src/future.rs:82:9
seed1_1    |   43: <warp::filter::and_then::State<T,F> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/filter/and_then.rs:99:44
seed1_1    |   44: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/filter/and_then.rs:74:9
seed1_1    |   45: <F as futures_core::future::TryFuture>::try_poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.15/src/future.rs:82:9
seed1_1    |   46: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/filter/or.rs:87:44
seed1_1    |   47: <warp::filter::and::State<T,TE,U> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/filter/and.rs:88:38
seed1_1    |   48: <warp::filter::and::AndFuture<T,U> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/filter/and.rs:65:9
seed1_1    |   49: <F as futures_core::future::TryFuture>::try_poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.15/src/future.rs:82:9
seed1_1    |   50: <warp::filter::service::FilteredFuture<F> as core::future::future::Future>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/filter/service.rs:128:41
seed1_1    |   51: scoped_tls::ScopedKey<T>::set
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
seed1_1    |   52: warp::route::set
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/route.rs:17:5
seed1_1    |   53: <warp::filter::service::FilteredFuture<F> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/git/checkouts/warp-3aafa59cffc62b0e/e457c1a/src/filter/service.rs:128:15
seed1_1    |   54: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/proto/h1/dispatch.rs:476:31
seed1_1    |   55: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/proto/h1/dispatch.rs:284:43
seed1_1    |   56: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/proto/h1/dispatch.rs:151:21
seed1_1    |   57: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/proto/h1/dispatch.rs:127:16
seed1_1    |   58: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/proto/h1/dispatch.rs:110:28
seed1_1    |   59: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/proto/h1/dispatch.rs:411:9
seed1_1    |   60: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/server/conn.rs:884:39
seed1_1    |   61: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/server/conn.rs:1063:30
seed1_1    |   62: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.10/src/server/conn.rs:1001:36
seed1_1    |   63: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
seed1_1    |   64: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
seed1_1    |   65: tokio::runtime::task::core::Core<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
seed1_1    |   66: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
seed1_1    |   67: core::ops::function::FnOnce::call_once
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/ops/function.rs:227:5
seed1_1    |   68: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panic.rs:344:9
seed1_1    |   69: std::panicking::try::do_call
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:379:40
seed1_1    |   70: __rust_try
seed1_1    |   71: std::panicking::try
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:343:19
seed1_1    |   72: std::panic::catch_unwind
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panic.rs:431:14
seed1_1    |   73: tokio::runtime::task::harness::Harness<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
seed1_1    |   74: tokio::runtime::task::raw::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
seed1_1    |   75: tokio::runtime::task::raw::RawTask::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
seed1_1    |   76: tokio::runtime::task::Notified<S>::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
seed1_1    |   77: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:349:13
seed1_1    |   78: tokio::coop::with_budget::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
seed1_1    |   79: std::thread::local::LocalKey<T>::try_with
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/thread/local.rs:272:16
seed1_1    |   80: std::thread::local::LocalKey<T>::with
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/thread/local.rs:248:9
seed1_1    |   81: tokio::coop::with_budget
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
seed1_1    |       tokio::coop::budget
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
seed1_1    |       tokio::runtime::thread_pool::worker::Context::run_task
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:348:9
seed1_1    |   82: tokio::runtime::thread_pool::worker::Context::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:320:24
seed1_1    |   83: tokio::runtime::thread_pool::worker::run::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:305:17
seed1_1    |   84: tokio::macros::scoped_tls::ScopedKey<T>::set
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
seed1_1    |   85: tokio::runtime::thread_pool::worker::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:302:5
seed1_1    |   86: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/thread_pool/worker.rs:281:45
seed1_1    |   87: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/task.rs:41:21
seed1_1    |   88: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
seed1_1    |   89: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
seed1_1    |   90: tokio::runtime::task::core::Core<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
seed1_1    |   91: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
seed1_1    |   92: core::ops::function::FnOnce::call_once
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/ops/function.rs:227:5
seed1_1    |   93: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panic.rs:344:9
seed1_1    |   94: std::panicking::try::do_call
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:379:40
seed1_1    |   95: __rust_try
seed1_1    |   96: std::panicking::try
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:343:19
seed1_1    |   97: std::panic::catch_unwind
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panic.rs:431:14
seed1_1    |   98: tokio::runtime::task::harness::Harness<T,S>::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
seed1_1    |   99: tokio::runtime::task::raw::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
seed1_1    |  100: tokio::runtime::task::raw::RawTask::poll
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
seed1_1    |  101: tokio::runtime::task::Notified<S>::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
seed1_1    |  102: tokio::runtime::blocking::pool::Inner::run
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:250:17
seed1_1    |  103: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:230:21
seed1_1    |  104: tokio::runtime::context::enter
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
seed1_1    |  105: tokio::runtime::handle::Handle::enter
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
seed1_1    |  106: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
seed1_1    |              at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/blocking/pool.rs:229:17
seed1_1    |  107: std::sys_common::backtrace::__rust_begin_short_backtrace
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/sys_common/backtrace.rs:125:18
seed1_1    |  108: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/thread/mod.rs:474:17
seed1_1    |  109: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panic.rs:344:9
seed1_1    |  110: std::panicking::try::do_call
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:379:40
seed1_1    |  111: __rust_try
seed1_1    |  112: std::panicking::try
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panicking.rs:343:19
seed1_1    |  113: std::panic::catch_unwind
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/panic.rs:431:14
seed1_1    |  114: std::thread::Builder::spawn_unchecked::{{closure}}
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/thread/mod.rs:473:30
seed1_1    |  115: core::ops::function::FnOnce::call_once{{vtable.shim}}
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/core/src/ops/function.rs:227:5
seed1_1    |  116: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/alloc/src/boxed.rs:1546:9
seed1_1    |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/alloc/src/boxed.rs:1546:9
seed1_1    |       std::sys::unix::thread::Thread::new::thread_start
seed1_1    |              at /rustc/0b417ab5cdfdedffd74fb22cf22d27033c851304/library/std/src/sys/unix/thread.rs:71:17
seed1_1    |  117: start_thread
seed1_1    |  118: clone

```

**Comment by sisou** [comment]
Hi, thanks for the report! I noticed this just yesterday evening as well! Will look into it now.

**Comment by sisou** [comment]
I pushed the fix and merged it into `lab-test`. Pull to update :wink:

**Comment by redmaner** [comment]
That was quick, nicely done
