### ISSUE TITLE
web-client: Not working for SvelteKit@2.0.0, Vite@5.4.11

### ISSUE THREAD

**Issue by Albermonte** [nimiq/core-rs-albatross#3214]
MRE: https://github.com/Albermonte/nimiq-svelte-demo

Following the setup instructions in either [@nimiq/core](https://www.npmjs.com/package/@nimiq/core) or [dev center](https://www.nimiq.com/developers/build/web-client/integrations/vite) for Vite results in the same error.

```
Internal server error: No known conditions for "./web" specifier in "@nimiq/core" package
  Plugin: vite:import-analysis
  File: /Users/albermonte/nimiq/nimiq-svelte-demo/src/routes/+page.svelte
      at e (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46041:25)
      at n (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46041:646)
      at o (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46041:1297)
      at resolveExportsOrImports (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46662:18)
      at resolveDeepImport (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46685:25)
      at tryNodeResolve (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46450:16)
      at ResolveIdContext.resolveId (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46200:19)
      at PluginContainer.resolveId (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49015:17)
      at async TransformPluginContext.resolve (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49175:15)
      at async normalizeUrl (file:///Users/albermonte/nimiq/nimiq-svelte-demo/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64034:26)
```

**Comment by sisou** [comment]
@Albermonte Please verify that https://github.com/Albermonte/nimiq-svelte-demo/pull/1 works for you. `pnpm build` runs successfully, but please check that the app actually does what you want from it. If it does, we can update the documentation accordingly.

**Comment by Albermonte** [comment]
Checked and it does work, just a small comment. The [worker.plugins](https://vite.dev/config/worker-options#worker-plugins) type is a function
