### ISSUE TITLE
Cannot request block 0 via RPC

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#365]
When requesting block 0 (the genesis block) via RPC, the node panics in calculating the previous macro block, underflow subtractions, probably more.

This is on the `bruno/rpc` branch.

**Comment by brunoffranca** [comment]
I'm looking at the `get_block_by_number` method but I can't find anything that could panic. What error are you getting?

**Comment by sisou** [comment]
That makes sense. If you could see where it panics, the bug likely wouldn't be there in the first place. Sometimes, these only show up when actually running the code.

Luckily, we are talking about the genesis block, so we don't need to run a network to generate blocks. It should even be possible to write a static test that calls the RPC method to verify it working for block 0.

Otherwise, here are the instructions to get a local node running and to request block 0 via RPC:

1. Create a node config file:
```
mkdir ~/.nimiq
vim ~/.nimiq/client.toml
```
2. Then add the following minimal config into the config file:
```toml
[network]
listen_addresses = ["/ip4/127.0.0.1/tcp/8443/ws"]

[rpc-server]
port = 8648
```
3. Run the node with `cargo run --bin nimiq-client`
4. Open a separate terminal in the core-rs-albatross repo and run `cargo run --bin nimiq-rpc -- block 0`
5. Watch the node panic with
```
'Called macro_block_before with block_number 0': /home/soeren/nimiq/core-rs-albatross/primitives/src/policy.rs:130
```
6. Fix the panic and repeat step 4 until valid JSON is returned.

**Comment by redmaner** [comment]
See logs below I captured when trying this:
```
 2021-10-24 16:50:19.091 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Called macro_block_before with block_number 0': /build/primitives/src/policy.rs:130
   0: log_panics::init::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:606:17
   2: std::panicking::begin_panic::{{closure}}
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:522:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/sys_common/backtrace.rs:139:18
   4: std::panicking::begin_panic
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:521:12
   5: nimiq_primitives::policy::macro_block_before
             at /build/primitives/src/policy.rs:130:9
   6: nimiq_blockchain::abstract_blockchain::AbstractBlockchain::get_slot_owner_at
             at /build/blockchain/src/abstract_blockchain.rs:126:27
   7: nimiq_rpc_interface::types::Slot::from
             at /build/rpc-interface/src/types.rs:374:40
   8: nimiq_rpc_interface::types::Block::from_block
             at /build/rpc-interface/src/types.rs:253:35
   9: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_rpc_interface::blockchain::BlockchainInterface>::get_block_by_number::{{closure}}
             at /build/rpc-server/src/dispatchers/blockchain.rs:85:12
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/future.rs:119:9
  12: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}::{{closure}}::{{closure}}
             at /build/rpc-server/src/dispatchers/blockchain.rs:30:1
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  14: nimiq_jsonrpc_server::dispatch_method_with_args::{{closure}}
             at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1229607/nimiq-jsonrpc-server/src/lib.rs:480:18
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  16: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
             at /build/rpc-server/src/dispatchers/blockchain.rs:30:1
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  18: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/future.rs:119:9
  19: <nimiq_jsonrpc_server::ModularDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
             at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1229607/nimiq-jsonrpc-server/src/lib.rs:361:24
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  21: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/future.rs:119:9
  22: <nimiq_jsonrpc_server::AllowListDispatcher<D> as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
             at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1229607/nimiq-jsonrpc-server/src/lib.rs:423:13
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/future.rs:119:9
  25: nimiq_jsonrpc_server::Server<D>::handle_single_request::{{closure}}
             at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1229607/nimiq-jsonrpc-server/src/lib.rs:306:24
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  27: nimiq_jsonrpc_server::Server<D>::handle_request::{{closure}}
             at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1229607/nimiq-jsonrpc-server/src/lib.rs:276:17
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  29: nimiq_jsonrpc_server::Server<D>::handle_raw_request::{{closure}}
             at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1229607/nimiq-jsonrpc-server/src/lib.rs:253:28
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  31: nimiq_jsonrpc_server::Server<D>::run::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1229607/nimiq-jsonrpc-server/src/lib.rs:156:32
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/future/mod.rs:80:19
  33: <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.17/src/future.rs:82:9
  34: <warp::filter::and_then::State<T,F> as core::future::future::Future>::poll
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/filter/and_then.rs:99:44
  35: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/filter/and_then.rs:74:9
  36: <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.17/src/future.rs:82:9
  37: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/filter/or.rs:87:44
  38: <warp::filter::and::State<T,TE,U> as core::future::future::Future>::poll
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/filter/and.rs:88:38
  39: <warp::filter::and::AndFuture<T,U> as core::future::future::Future>::poll
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/filter/and.rs:65:9
  40: <F as futures_core::future::TryFuture>::try_poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.17/src/future.rs:82:9
  41: <warp::filter::service::FilteredFuture<F> as core::future::future::Future>::poll::{{closure}}
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/filter/service.rs:128:41
  42: scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  43: warp::route::set
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/route.rs:17:5
  44: <warp::filter::service::FilteredFuture<F> as core::future::future::Future>::poll
             at /usr/local/cargo/git/checkouts/warp-5972215cbaf1f1ca/45ac5ae/src/filter/service.rs:128:15
  45: <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:491:35
  46: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:297:43
  47: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:161:21
  48: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:137:16
  49: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:120:28
  50: <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/proto/h1/dispatch.rs:424:9
  51: <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/server/conn.rs:1061:47
  52: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/server/conn.rs:1265:30
  53: <hyper::server::conn::spawn_all::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.13/src/server/conn.rs:1202:36
  54: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:161:17
  55: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/loom/std/unsafe_cell.rs:14:9
  56: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:151:13
  57: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:461:19
  58: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panic/unwind_safe.rs:271:9
  59: std::panicking::try::do_call
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:403:40
  60: __rust_try
  61: std::panicking::try
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:367:19
  62: std::panic::catch_unwind
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panic.rs:133:14
  63: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:449:18
  64: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:98:27
  65: tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:53:15
  66: tokio::runtime::task::raw::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:113:5
  67: tokio::runtime::task::raw::RawTask::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:70:18
  68: tokio::runtime::task::LocalNotified<S>::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/mod.rs:343:9
  69: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:443:21
  70: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  71: std::thread::local::LocalKey<T>::try_with
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/thread/local.rs:399:16
  72: std::thread::local::LocalKey<T>::with
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/thread/local.rs:375:9
  73: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
      tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
      tokio::runtime::thread_pool::worker::Context::run_task
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:419:9
  74: tokio::runtime::thread_pool::worker::Context::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:386:24
  75: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:371:17
  76: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  77: tokio::runtime::thread_pool::worker::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:368:5
  78: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/thread_pool/worker.rs:347:45
  79: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/task.rs:42:21
  80: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:161:17
  81: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/loom/std/unsafe_cell.rs:14:9
  82: tokio::runtime::task::core::CoreStage<T>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:151:13
  83: tokio::runtime::task::harness::poll_future::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:461:19
  84: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panic/unwind_safe.rs:271:9
  85: std::panicking::try::do_call
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:403:40
  86: __rust_try
  87: std::panicking::try
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:367:19
  88: std::panic::catch_unwind
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panic.rs:133:14
  89: tokio::runtime::task::harness::poll_future
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:449:18
  90: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:98:27
  91: tokio::runtime::task::harness::Harness<T,S>::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:53:15
  92: tokio::runtime::task::raw::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:113:5
  93: tokio::runtime::task::raw::RawTask::poll
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:70:18
  94: tokio::runtime::task::UnownedTask<S>::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/mod.rs:379:9
  95: tokio::runtime::blocking::pool::Inner::run
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/pool.rs:265:17
  96: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/pool.rs:245:17
  97: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/sys_common/backtrace.rs:123:18
  98: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/thread/mod.rs:483:17
  99: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panic/unwind_safe.rs:271:9
 100: std::panicking::try::do_call
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:403:40
 101: __rust_try
 102: std::panicking::try
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:367:19
 103: std::panic::catch_unwind
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panic.rs:133:14
 104: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/thread/mod.rs:482:30
 105: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
 106: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/sys/unix/thread.rs:106:17

```
