### ISSUE TITLE
Failed to compute transactions root, micro blocks missing

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#38]
## Stack trace

```
logs/devnet_validator_13.log- INFO  consensus            | Now at block #38912
logs/devnet_validator_13.log- WARN  staking_contract     | Slashing NQ26 349P FBHS 4D6Y JR21 164P Q709 NQKP F12D with 6.49077
logs/devnet_validator_13.log: ERROR panic                | thread 'tokio-runtime-worker-1' panicked at 'Failed to compute transactions root, micro blocks missing': src/libcore/option.rs:1185
logs/devnet_validator_13.log-stack backtrace:
logs/devnet_validator_13.log-   0: log_panics::init::{{closure}}
logs/devnet_validator_13.log-   1: std::panicking::rust_panic_with_hook
logs/devnet_validator_13.log-             at src/libstd/panicking.rs:468
logs/devnet_validator_13.log-   2: std::panicking::continue_panic_fmt
logs/devnet_validator_13.log-             at src/libstd/panicking.rs:373
logs/devnet_validator_13.log-   3: rust_begin_unwind
logs/devnet_validator_13.log-             at src/libstd/panicking.rs:302
logs/devnet_validator_13.log-   4: core::panicking::panic_fmt
logs/devnet_validator_13.log-             at src/libcore/panicking.rs:139
logs/devnet_validator_13.log-   5: core::option::expect_failed
logs/devnet_validator_13.log-             at src/libcore/option.rs:1185
logs/devnet_validator_13.log-   6: nimiq_block_production_albatross::BlockProducer::next_macro_header
logs/devnet_validator_13.log-   7: nimiq_block_production_albatross::BlockProducer::next_macro_block_proposal
logs/devnet_validator_13.log-   8: nimiq_validator::validator::Validator::produce_macro_block
logs/devnet_validator_13.log-   9: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
logs/devnet_validator_13.log-  10: futures::task_impl::Spawn<T>::poll_future_notify
logs/devnet_validator_13.log-  11: std::panicking::try::do_call
logs/devnet_validator_13.log-  12: __rust_maybe_catch_panic
logs/devnet_validator_13.log-             at src/libpanic_unwind/lib.rs:79
logs/devnet_validator_11.log- INFO  consensus            | Now at block #30014
logs/devnet_validator_11.log- INFO  consensus            | Now at block #30015
```

**Comment by jgraef** [comment]
This error happens quite frequently. The DevNet is running for over 2 days and the error occured 183 times.

Another log excerpt:

```
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log- DEBUG validator            | Completed view change to #343936.1
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log- DEBUG validator_network    | View change already complete: #343936.1
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log- DEBUG consensus            | Now at block #343936
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log- DEBUG blockchain           | Slash inherent: view change: 3.10000 NIM, NQ51 HX56 XNN0 KXQC VJ93 M3Q8 J2EB 1KX5 D5MG
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log- DEBUG blockchain           | get_block_at didn't return first block of epoch: block_height=343937
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log: ERROR panic                | thread 'tokio-runtime-worker-4' panicked at 'Failed to compute transactions root, micro blocks missing': src/libcore/option.rs:1187
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-stack backtrace:
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   0: log_panics::init::{{closure}}
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   1: std::panicking::rust_panic_with_hook
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-             at src/libstd/panicking.rs:468
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   2: std::panicking::continue_panic_fmt
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-             at src/libstd/panicking.rs:373
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   3: rust_begin_unwind
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-             at src/libstd/panicking.rs:302
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   4: core::panicking::panic_fmt
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-             at src/libcore/panicking.rs:141
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   5: core::option::expect_failed
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-             at src/libcore/option.rs:1187
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   6: nimiq_block_production_albatross::BlockProducer::next_macro_header
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   7: nimiq_block_production_albatross::BlockProducer::next_macro_block_proposal
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   8: nimiq_validator::validator::Validator::produce_macro_block
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-   9: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-  10: futures::task_impl::Spawn<T>::poll_future_notify
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-  11: std::panicking::try::do_call
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-  12: __rust_maybe_catch_panic
logs/devnet_validator.9.ghcfvw0wyf3fugvz34ov0bwz3.log-             at src/libpanic_unwind/lib.rs:79
```

**Comment by jgraef** [comment]
This happens because view changes are still being made even after a proposal was received. When we receive a proposal we have to stop the view change timer.

**Comment by jgraef** [comment]
See #54

**Comment by brunoffranca** [comment]
This should also not be relevant after the change to Tendermint.
