### ISSUE TITLE
Can't find previous block panic

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#418]
Observed during the following CI runs:
https://github.com/nimiq/core-rs-albatross/runs/4180299893?check_suite_focus=true
https://github.com/nimiq/core-rs-albatross/runs/4191934054?check_suite_focus=true
https://github.com/nimiq/core-rs-albatross/runs/4195406721?check_suite_focus=true

Backtrace:
```
2021-11-11 16:42:19.464 ^[[31mERROR^[[0m panic                | thread 'tokio-runtime-worker' panicked at 'Can't find previous block!': blockchain/src/abstract_blockchain.rs:182
   0: log_panics::init::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/panicking.rs:106:14
   6: core::panicking::panic_display
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/panicking.rs:62:5
   7: core::option::expect_failed
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/option.rs:1637:5
   8: core::option::Option<T>::expect
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/option.rs:709:21
   9: nimiq_blockchain::abstract_blockchain::AbstractBlockchain::get_slot_owner_number_at
             at blockchain/src/abstract_blockchain.rs:180:20
  10: nimiq_blockchain::abstract_blockchain::AbstractBlockchain::get_slot_owner_at
             at blockchain/src/abstract_blockchain.rs:139:13
  11: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::is_our_turn
             at validator/src/micro.rs:117:25
  12: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::next::{{closure}}
             at validator/src/micro.rs:88:24
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/future/mod.rs:80:19
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/future/future.rs:119:9
  15: futures_util::future::future::FutureExt::poll_unpin
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/future/future/mod.rs:562:9
  16: <nimiq_validator::micro::ProduceMicroBlock<TValidatorNetwork> as futures_core::stream::Stream>::poll_next
             at validator/src/micro.rs:244:42
  17: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.17/src/stream/stream/mod.rs:1474:9
  18: nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork>::poll_micro
             at validator/src/validator.rs:481:46
  19: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
             at validator/src/validator.rs:664:17
  20: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/core.rs:161:17
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/loom/std/unsafe_cell.rs:14:9
  22: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/core.rs:151:13
  23: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/task/harness.rs:461:19
  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/core/src/panic/unwind_safe.rs:271:9
  25: std::panicking::try::do_call
             at /rustc/82af160c2cb9c349a0373cba98d8ad7f911f0d34/library/std/src/panicking.rs:406:40
  26: __rust_try
```

**Comment by jeffesquivels** [comment]
Closing this as the panic itself was fixed by 90ea8354148e63ae02acbf18f3f9133f8135aa1e. Still, this is an incomplete fix, the final fix will be tracked in #428.
