### ISSUE TITLE
Panic due to index out of bounds when reverting inherents

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#423]
Observed in the following CI run:
https://github.com/nimiq/core-rs-albatross/runs/4218984938?check_suite_focus=true

```
temp-logs/20211116_004241/Validator3.txt:3947: 2021-11-16 00:56:22.416 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0': primitives/account/src/accounts.rs:426
temp-logs/20211116_004241/Validator3.txt:3988:  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_004241/Validator3.txt:3989:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_004241/Validator3.txt:3995:  24: std::panic::catch_unwind
temp-logs/20211116_004241/Validator3.txt:3996:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panic.rs:133:14
temp-logs/20211116_004241/Validator3.txt:4017:  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_004241/Validator3.txt:4018:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_004241/Validator3.txt:4024:  39: std::panic::catch_unwind
temp-logs/20211116_004241/Validator3.txt:4025:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panic.rs:133:14
temp-logs/20211116_004241/Validator3.txt:4046: 2021-11-16 00:56:22.724 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'blockchain.push_history_sync() should not panic: JoinError::Panic(...)': /home/runner/work/core-rs-albatross/core-rs-albatross/consensus/src/sync/history/sync_stream.rs:118
temp-logs/20211116_004241/Validator3.txt:4095:  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_004241/Validator3.txt:4096:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_004241/Validator3.txt:4102:  28: std::panic::catch_unwind
temp-logs/20211116_004241/Validator3.txt:4103:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panic.rs:133:14
temp-logs/20211116_004241/Validator3.txt:4150:  50: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_004241/Validator3.txt:4151:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_004241/Validator3.txt:4157:  54: std::panic::catch_unwind
temp-logs/20211116_004241/Validator3.txt:4158:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panic.rs:133:14
temp-logs/20211116_004241/Validator3.txt:4179:  65: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_004241/Validator3.txt:4180:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_004241/Validator3.txt:4186:  69: std::panic::catch_unwind
temp-logs/20211116_004241/Validator3.txt:4187:             at /rustc/ad442399756573dccacb314b6bf8079964bcc72a/library/std/src/panic.rs:133:14
```

**Comment by viquezclaudio** [comment]
https://github.com/nimiq/core-rs-albatross/runs/4221541604?check_suite_focus=true

**Comment by jeffesquivels** [comment]
The problem is related to the fact that [we use](https://github.com/nimiq/core-rs-albatross/blob/aeb9052ce696eb084bf491b36b938269308e9c17/primitives/account/src/accounts.rs#L426) the index from the `receipt` to retrieve the correct inherent from the `inherents` array while reverting the blocks. In theory, this should work since [we create](https://github.com/nimiq/core-rs-albatross/blob/aeb9052ce696eb084bf491b36b938269308e9c17/primitives/account/src/accounts.rs#L399) the `receipts` (while pushing the block) iterating over the `inherents` array, but this inherent array is created by processing fork proofs and view changes, so if the any of these two are calculated differently between the push path and the revert path, there would be chance for a mismatch in the size of that array in both paths.

And indeed, this is what is happening, the push path uses a `ViewChanges` instance that [is created](https://github.com/nimiq/core-rs-albatross/blob/ebbf9b56b5636d48c01d9a063da14dcb3ea2347a/blockchain/src/blockchain/accounts.rs#L67) by [calling `next_view_number()`](https://github.com/nimiq/core-rs-albatross/blob/ebbf9b56b5636d48c01d9a063da14dcb3ea2347a/blockchain/src/blockchain/push.rs#L247) on the previous block, while  the revert path [calls `view_number()`](https://github.com/nimiq/core-rs-albatross/blob/ebbf9b56b5636d48c01d9a063da14dcb3ea2347a/blockchain/src/blockchain/history_sync.rs#L365) on that same previous block.

If we inspection these two functions, we can see that they differ for the case where the block is a `MacroBlock`:

```
    pub fn view_number(&self) -> u32 {
        match self {
            Block::Macro(ref block) => block.header.view_number,
            Block::Micro(ref block) => block.header.view_number,
        }
    }
```

```
    pub fn next_view_number(&self) -> u32 {
        match self {
            // If the previous block was a macro block, this resets the view number.
            Block::Macro(_) => 0,
            // Otherwise we are now at the view number of the previous block.
            Block::Micro(ref block) => block.header.view_number,
        }
    }
 ```

This would have an impact when creating `ViewChanges`, since the value for `first_view_number` [here](https://github.com/nimiq/core-rs-albatross/blob/ebbf9b56b5636d48c01d9a063da14dcb3ea2347a/primitives/block/src/view_change.rs#L59) would be different:

```
        if first_view_number < last_view_number {
```

So, for this to be the cause of the problem, we require the block previous to the panic to be a MacroBlock with a `view_number` != 0, looking into the logs for [this occurence](https://github.com/nimiq/core-rs-albatross/runs/4221541604?check_suite_focus=true) of the issue we can see that this condition is indeed fulfilled:

`2021-11-16 07:26:06.240 INFO  nimiq_client         | Consensus established: true - Head: #352.1- 9d7a220bc37cf593434780b8ef7badfc37a104f162f91848d7d3adaf2078b108, Peers: 3`

Block 352 is a MacroBlock (32 * 11 = 352) and it's `view_number` is 1, which means that the `ViewChanges` calculated when pushing the block would contain one item, whereas the one calculated when reverting would have no items at all, thus creating a zero-size array, which triggers the index out of bounds panic. QED 😀.

**Comment by jsdanielh** [comment]
Found another occurrence of this issue [in this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/1917362058):
```
2022-03-01 17:11:26.239 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0': primitives/account/src/accounts.rs:426
   0: log_panics::init::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panicking.rs:143:14
   6: core::panicking::panic_bounds_check
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panicking.rs:84:5
   7: nimiq_account::accounts::Accounts::revert_inherents
             at primitives/account/src/accounts.rs:426:22
   8: nimiq_account::accounts::Accounts::revert_batch
             at primitives/account/src/accounts.rs:203:9
   9: nimiq_account::accounts::Accounts::revert
             at primitives/account/src/accounts.rs:155:9
  10: nimiq_blockchain::blockchain::accounts::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::revert_accounts
             at blockchain/src/blockchain/accounts.rs:161:25
  11: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::revert_blocks
             at blockchain/src/blockchain/history_sync.rs:464:21
  12: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::revert_to_common_state
             at blockchain/src/blockchain/history_sync.rs:431:17
  13: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::extend_history_sync
             at blockchain/src/blockchain/history_sync.rs:206:32
  14: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::push_history_sync
             at blockchain/src/blockchain/history_sync.rs:147:9
  15: nimiq_consensus::sync::history::sync_stream::<impl nimiq_consensus::sync::history::sync::HistorySync<TNetwork>>::poll_cluster::{{closure}}::{{closure}}
             at consensus/src/sync/history/sync_stream.rs:112:33
  16: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
  17: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  19: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  20: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
  22: std::panicking::try::do_call
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
  23: __rust_try
  24: std::panicking::try
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
  25: std::panic::catch_unwind
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
  26: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  27: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  28: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  29: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  30: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  31: tokio::runtime::task::UnownedTask<S>::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
  32: tokio::runtime::blocking::pool::Task::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
  33: tokio::runtime::blocking::pool::Inner::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
  34: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
  35: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:122:18
  36: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:498:17
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
  38: std::panicking::try::do_call
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
  39: __rust_try
  40: std::panicking::try
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
  41: std::panic::catch_unwind
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
  42: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:497:30
  43: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/ops/function.rs:227:5
  44: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys/unix/thread.rs:108:17
  45: start_thread
  46: clone
```

**Comment by jeffesquivels** [comment]
> Found another occurrence of this issue [in this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/1917362058):
> [...]

The issue was the same as the original (fixed) one, but occurring through a different execution path: the original issue was because we used the wrong previous view number when pushing a block that extends the chain (which was fixed), and in this case, the problem was because we were also using the wrong previous view number when pushing a block during a rebranch of the chain.
