### ISSUE TITLE
Block's predecessor part of the chain check panicked

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#427]
In some CI runs, the following panic has been observed:

```
temp-logs/20211116_092242/Validator2.txt:4163: 2021-11-16 09:33:38.296 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value': blockchain/src/blockchain/verify.rs:42
temp-logs/20211116_092242/Validator2.txt:4176:   6: core::panicking::panic
temp-logs/20211116_092242/Validator2.txt:4242:  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_092242/Validator2.txt:4243:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_092242/Validator2.txt:4249:  43: std::panic::catch_unwind
temp-logs/20211116_092242/Validator2.txt:4250:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panic.rs:133:14
temp-logs/20211116_092242/Validator2.txt:4297:  65: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_092242/Validator2.txt:4298:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_092242/Validator2.txt:4304:  69: std::panic::catch_unwind
temp-logs/20211116_092242/Validator2.txt:4305:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panic.rs:133:14
temp-logs/20211116_092242/Validator2.txt:4326:  80: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_092242/Validator2.txt:4327:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_092242/Validator2.txt:4333:  84: std::panic::catch_unwind
temp-logs/20211116_092242/Validator2.txt:4334:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panic.rs:133:14
temp-logs/20211116_092242/Validator4.txt:3277: 2021-11-16 09:33:37.786 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value': blockchain/src/blockchain/verify.rs:42
temp-logs/20211116_092242/Validator4.txt:3290:   6: core::panicking::panic
temp-logs/20211116_092242/Validator4.txt:3356:  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_092242/Validator4.txt:3357:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_092242/Validator4.txt:3363:  43: std::panic::catch_unwind
temp-logs/20211116_092242/Validator4.txt:3364:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panic.rs:133:14
temp-logs/20211116_092242/Validator4.txt:3411:  65: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_092242/Validator4.txt:3412:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_092242/Validator4.txt:3418:  69: std::panic::catch_unwind
temp-logs/20211116_092242/Validator4.txt:3419:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panic.rs:133:14
temp-logs/20211116_092242/Validator4.txt:3440:  80: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211116_092242/Validator4.txt:3441:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211116_092242/Validator4.txt:3447:  84: std::panic::catch_unwind
temp-logs/20211116_092242/Validator4.txt:3448:             at /rustc/891ca5f63c3b3cfe3939710a728671243e881ed6/library/std/src/panic.rs:133:14
```
The unwrap comes from a function that checks if the block's immediate predecessor is part of the chain, so this might be related to 
[#418](https://github.com/nimiq/core-rs-albatross/issues/418) however the failing function is different, so this needs further investigation.
Some examples of this failure:
https://github.com/nimiq/core-rs-albatross/runs/4222566267?check_suite_focus=true
https://github.com/nimiq/core-rs-albatross/runs/4156046236?check_suite_focus=true

**Comment by jeffesquivels** [comment]
Closing this as the panic itself was fixed by 3b52b01bc7f2f2a781526aabaad492bb09b36648. Still, this is a partial fix, the missing part will be tracked in #429.
