### ISSUE TITLE
assertion failed: self.peer_id.is_none()' in ConnectionPoolHandler

### ISSUE THREAD

**Issue by fiaxh** [nimiq/core-rs-albatross#438]
```
temp-logs/20211119_221854/Validator4.txt:496: 2021-11-19 22:21:08.715 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'assertion failed: self.peer_id.is_none()': network-libp2p/src/connection_pool/handler.rs:163
temp-logs/20211119_221854/Validator4.txt:509:   6: core::panicking::panic
temp-logs/20211119_221854/Validator4.txt:533:  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211119_221854/Validator4.txt:534:             at /rustc/cc946fcd326f7d85d4af096efdc73538622568e9/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211119_221854/Validator4.txt:540:  22: std::panic::catch_unwind
temp-logs/20211119_221854/Validator4.txt:541:             at /rustc/cc946fcd326f7d85d4af096efdc73538622568e9/library/std/src/panic.rs:133:14
temp-logs/20211119_221854/Validator4.txt:588:  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211119_221854/Validator4.txt:589:             at /rustc/cc946fcd326f7d85d4af096efdc73538622568e9/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211119_221854/Validator4.txt:595:  48: std::panic::catch_unwind
temp-logs/20211119_221854/Validator4.txt:596:             at /rustc/cc946fcd326f7d85d4af096efdc73538622568e9/library/std/src/panic.rs:133:14
temp-logs/20211119_221854/Validator4.txt:617:  59: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
temp-logs/20211119_221854/Validator4.txt:618:             at /rustc/cc946fcd326f7d85d4af096efdc73538622568e9/library/core/src/panic/unwind_safe.rs:271:9
temp-logs/20211119_221854/Validator4.txt:624:  63: std::panic::catch_unwind
temp-logs/20211119_221854/Validator4.txt:625:             at /rustc/cc946fcd326f7d85d4af096efdc73538622568e9/library/std/src/panic.rs:133:14
```

See https://github.com/nimiq/core-rs-albatross/runs/4269718161?check_suite_focus=true

[reconnect-test-logs-with-spammer.zip](https://github.com/nimiq/core-rs-albatross/files/7573479/reconnect-test-logs-with-spammer.4.zip)

**Comment by viquezclaudio** [comment]
A similar [issue](https://github.com/nimiq/core-rs-albatross/issues/379) was closed some days ago, including it here as a reference.
