### ISSUE TITLE
Panic in consensus sync clustering

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#498]
In devnet RC2 a panic in consensus `sync_clustering` was seen:
```
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:  2021-12-03 19:38:15.885 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Agent should be present PeerId("12D3KooWMcaDYVPpDUnXFVFHHSC4fZBaZHqgsVYPrMqyVmAuP22n") cluster 668': /home/jeffrey/working_dir/nimiq/core-rs-albatross/consensus/src/sync/history/sync_clustering.rs:440
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    0: log_panics::init::{{closure}}
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    1: std::panicking::rust_panic_with_hook
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/std/src/panicking.rs:610:17
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/std/src/panicking.rs:502:13
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/std/src/sys_common/backtrace.rs:139:18
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    4: rust_begin_unwind
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/std/src/panicking.rs:498:5
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    5: core::panicking::panic_fmt
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/core/src/panicking.rs:107:14
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    6: nimiq_consensus::sync::history::sync_clustering::<impl nimiq_consensus::sync::history::sync::HistorySync<TNetwork>>::finish_cluster
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    7: nimiq_consensus::sync::history::sync_stream::<impl futures_core::stream::Stream for nimiq_consensus::sync::history::sync::HistorySync<TNetwork>>::poll_next
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    8: <nimiq_consensus::sync::block_queue::BlockQueue<N,TReq> as futures_core::stream::Stream>::poll_next
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:    9: tokio::runtime::task::harness::poll_future
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   10: tokio::runtime::task::raw::poll
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   11: tokio::runtime::thread_pool::worker::Context::run_task
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   12: tokio::runtime::task::raw::poll
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   13: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   14: core::ops::function::FnOnce::call_once{{vtable.shim}}
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/alloc/src/boxed.rs:1694:9
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/alloc/src/boxed.rs:1694:9
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:       std::sys::unix::thread::Thread::new::thread_start
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:              at /rustc/b426445c60b4faab6e96d2b866164d478680abf6/library/std/src/sys/unix/thread.rs:106:17
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   16: start_thread
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:   17: clone
```

**Comment by jsdanielh** [comment]
Issue seems to be caused by this sequence of events:
1. A connection to the peer is closed:
```
Dec 03 19:38:14 ip-172-31-7-48 nimiq-client[106507]:  2021-12-03 19:38:14.507 INFO  network              | Connection closed with peer 12D3KooWMcaDYVPpDUnXFVFHHSC4fZBaZHqgsVYPrMqyVmAuP22n, Dialer { address: "/ip4/172.31.11.42/tcp/8443/ws/p2p/12D3KooWMcaDYVPpDUnXFVFHHSC4fZBaZHqgsVYPrMqyVmAuP22n" }, connections established: 0
```
2. Since the connection is closed, history sync realizes and remove the peer from `self.agents` [here](https://github.com/nimiq/core-rs-albatross/blob/albatross/consensus/src/sync/history/sync_stream.rs#L31).
3. Then panic happens:
```
Dec 03 19:38:15 ip-172-31-7-48 nimiq-client[106507]:  2021-12-03 19:38:15.885 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Agent should be present PeerId("12D3KooWMcaDYVPpDUnXFVFHHSC4fZBaZHqgsVYPrMqyVmAuP22n") cluster 668': /home/jeffrey/working_dir/nimiq/core-rs-albatross/consensus/src/sync/history/sync_clustering.rs:440
```
