### ISSUE TITLE
Panic in history sync: Agent should be present

### ISSUE THREAD

**Issue by styppo** [nimiq/core-rs-albatross#633]
CI Run: [#1545](https://github.com/nimiq/core-rs-albatross/runs/5438999539?check_suite_focus=true)
Job: `FourValidatorsReconnectSpammer`
Node: `spammer`
Related: #498 
Logs: [1545 FourValidatorsReconnectSpammer.zip](https://github.com/nimiq/core-rs-albatross/files/8194911/1545.FourValidatorsReconnectSpammer-logs.zip)

```
thread 'tokio-runtime-worker' panicked at 'Agent should be present PeerId("12D3KooWPmFvhx6vUCPX65UJeg3GSTkTEjvqzNNS8RDspiLmepBq") cluster 0': /home/runner/work/core-rs-albatross/core-rs-albatross/consensus/src/sync/history/sync_clustering.rs:452
   0: log_panics::init::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/panicking.rs:143:14
   6: nimiq_consensus::sync::history::sync_clustering::<impl nimiq_consensus::sync::history::sync::HistorySync<TNetwork>>::finish_cluster::{{closure}}
             at consensus/src/sync/history/sync_clustering.rs:452:25
   7: core::option::Option<T>::unwrap_or_else
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/option.rs:802:21
   8: nimiq_consensus::sync::history::sync_clustering::<impl nimiq_consensus::sync::history::sync::HistorySync<TNetwork>>::finish_cluster
             at consensus/src/sync/history/sync_clustering.rs:451:32
   9: nimiq_consensus::sync::history::sync_stream::<impl nimiq_consensus::sync::history::sync::HistorySync<TNetwork>>::poll_job_queue
             at consensus/src/sync/history/sync_stream.rs:189:21
  10: nimiq_consensus::sync::history::sync_stream::<impl futures_core::stream::Stream for nimiq_consensus::sync::history::sync::HistorySync<TNetwork>>::poll_next
             at consensus/src/sync/history/sync_stream.rs:236:9
  11: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  12: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  13: <nimiq_consensus::sync::request_component::BlockRequestComponent<TPeer> as futures_core::stream::Stream>::poll_next
             at consensus/src/sync/request_component.rs:153:41
  14: <nimiq_consensus::sync::block_queue::BlockQueue<N,TReq> as futures_core::stream::Stream>::poll_next
             at consensus/src/sync/block_queue.rs:622:19
  15: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  16: <nimiq_consensus::consensus::Consensus<N> as core::future::future::Future>::poll
             at consensus/src/consensus/mod.rs:278:46
  17: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  19: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  20: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/panic/unwind_safe.rs:271:9
  22: std::panicking::try::do_call
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:492:40
  23: __rust_try
  24: std::panicking::try
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:456:19
  25: std::panic::catch_unwind
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panic.rs:137:14
  26: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  27: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  28: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  29: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  30: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  31: tokio::runtime::task::LocalNotified<S>::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
  32: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:425:13
  33: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  34: std::thread::local::LocalKey<T>::try_with
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/thread/local.rs:442:16
  35: std::thread::local::LocalKey<T>::with
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/thread/local.rs:418:9
  36: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
      tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
      tokio::runtime::thread_pool::worker::Context::run_task
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:424:9
  37: tokio::runtime::thread_pool::worker::Context::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:391:24
  38: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:376:17
  39: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  40: tokio::runtime::thread_pool::worker::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:373:5
  41: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:352:45
  42: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
  43: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  44: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  45: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  46: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  47: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/panic/unwind_safe.rs:271:9
  48: std::panicking::try::do_call
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:492:40
  49: __rust_try
  50: std::panicking::try
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:456:19
  51: std::panic::catch_unwind
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panic.rs:137:14
  52: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  53: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  55: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  56: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  57: tokio::runtime::task::UnownedTask<S>::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
  58: tokio::runtime::blocking::pool::Task::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
  59: tokio::runtime::blocking::pool::Inner::run
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
  60: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
  61: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/sys_common/backtrace.rs:122:18
  62: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/thread/mod.rs:498:17
  63: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/panic/unwind_safe.rs:271:9
  64: std::panicking::try::do_call
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:492:40
  65: __rust_try
  66: std::panicking::try
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panicking.rs:456:19
  67: std::panic::catch_unwind
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/panic.rs:137:14
  68: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/thread/mod.rs:497:30
  69: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/core/src/ops/function.rs:227:5
  70: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c274e4969f058b1c644243181ece9f829efa7594/library/std/src/sys/unix/thread.rs:108:17
  71: start_thread
  72: clone
 ```

**Comment by fiaxh** [comment]
<details>
<summary>Happened in a devnet</summary>

```
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:03.296316Z DEBUG behaviour            | Maintaining peers: connected=3, dialing=0, failed=0, down=18 | addresses: connected=3, dialing=0, failed=0, down=0
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:03.296448Z INFO  network              | Connection closed with peer 12D3KooWDySSeeCz1bvqy1RN7EVcdwB7uNW3PFniTHgWD1zKAtLM, Listener { local_addr: "/ip4/172.31.14.181/tcp/8443/ws", send_back_addr: "/ip4/172.31.9.186/tcp/39432/ws" }, connections established: 0
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:03.297450Z DEBUG sync_stream          | Processing epoch #466 (817 history items)
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:03.441112Z DEBUG push                 | Accepted block #59497.0:MI:4408d39af4 with 13 transactions (extend)
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.121885Z INFO  network              | Connection closed because: IO(Custom { kind: Other, error: Closed })
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.121929Z WARN  lock_api             | lock held for a long time: 680.823422ms - lock_api::rwlock::RwLockUpgradableReadGuard<parking_lot::raw_rwlock::RawRwLock, nimiq_blockchain::blockchain::blockchain::Blockchain>
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.122036Z WARN  lock_api             |    0: lock_api::report_lock_time
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    1: nimiq_blockchain::blockchain::push::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::extend
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    2: nimiq_blockchain::blockchain::push::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::do_push
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    3: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    4: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    5: tokio::runtime::task::harness::Harness<T,S>::poll
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    6: tokio::runtime::blocking::pool::Inner::run
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    7: std::sys_common::backtrace::__rust_begin_short_backtrace
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    8: core::ops::function::FnOnce::call_once{{vtable.shim}}
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:    9: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/alloc/src/boxed.rs:1853:9
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:       std::sys::unix::thread::Thread::new::thread_start
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:              at /rustc/3c17c84a386e7badf6b2c6018d172496b3a28a04/library/std/src/sys/unix/thread.rs:108:17
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:   10: start_thread
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:   11: clone
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]:     
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.122154Z WARN  history_sync         | Rejecting block #59552.0:MA:867418e016 - wrong parent election hash (607259569e46c7a4a4369fe2425413bce04c4d1375136857f50f0994b696a4fe != 8e705189763756e87bc32de6725bacee017aae6eae32fa2297160f8b1896d776)
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.122429Z DEBUG cluster              | SyncClusterResult From<Result<T, E>> encountered error: Orphan
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.122445Z DEBUG sync_stream          | PushBatchSet from cluster_id 5 completed with result: Error
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.122453Z DEBUG sync_clustering      | Failed to push epoch from cluster 5: Error
Mar 23 16:50:04 ip-172-31-14-181 nimiq-client[453847]: 2022-03-23T16:50:04.123580Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Agent should be present PeerId("12D3KooWDySSeeCz1bvqy1RN7EVcdwB7uNW3PFniTHgWD1zKAtLM") cluster 5': /home/jeffrey/working_dir/nimiq/core-rs-albatross/consensus/src/sync/history/sync_clustering.rs:450
```
</details>
