### ISSUE TITLE
Panic in tendermint: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by styppo** [nimiq/core-rs-albatross#645]
CI run: [#1588](https://github.com/nimiq/core-rs-albatross/runs/5472687706?check_suite_focus=true)
Job: `MacroBlockProduction`
Node: `validator3`
Logs: [1588 MacroBlockProduction.zip](https://github.com/nimiq/core-rs-albatross/files/8211404/1588.MacroBlockProduction.zip)

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value': /home/runner/work/core-rs-albatross/core-rs-albatross/validator/src/tendermint.rs:395
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/std/src/panicking.rs:586:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/core/src/panicking.rs:143:14
   6: core::panicking::panic
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/core/src/panicking.rs:48:5
   7: <nimiq_validator::tendermint::TendermintInterface<TValidatorNetwork> as nimiq_tendermint::outside_deps::TendermintOutsideDeps>::hash_proposal
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: nimiq_tendermint::stream::expect_block::{{closure}}
  10: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
  11: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
  12: futures_util::stream::stream::StreamExt::poll_next_unpin
  13: <futures_util::stream::select_all::SelectAll<St> as futures_core::stream::Stream>::poll_next
  14: <nimiq_tendermint::stream::TendermintStreamWrapper<DepsTy,ProposalTy,ProofTy,ResultTy> as futures_core::stream::Stream>::poll_next
  15: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
  16: tokio::runtime::task::harness::poll_future
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/std/src/sys/unix/thread.rs:108:17
  28: start_thread
  29: clone
```

**Comment by viquezclaudio** [comment]
- [ ] Testing 1
- [ ] Testing 2

**Comment by hrxi** [comment]
Looking into this right now.
