### ISSUE TITLE
Panic: Failed to compute accounts hash during block production

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#701]
When running the devnet docker scenario with:

- 1 seed node
- 5 validators
- 1 spammer
- 1 Albagen

The following panic was observed in validator 2 (seed2 in attached logs):

```
^[[36mseed2_1    |^[[0m ^[[2m2022-03-19T15:26:46.372387Z^[[0m ^[[31mERROR^[[0m ^[[2mpanic               ^[[0m | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: InsufficientFunds { needed: Coin(15322417), balance: Coin(3830604) }': block-production/src/lib.rs:84
^[[36mseed2_1    |^[[0m    0: log_panics::init::{{closure}}
^[[36mseed2_1    |^[[0m    1: std::panicking::rust_panic_with_hook
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:610:17
^[[36mseed2_1    |^[[0m    2: std::panicking::begin_panic_handler::{{closure}}
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:502:13
^[[36mseed2_1    |^[[0m    3: std::sys_common::backtrace::__rust_end_short_backtrace
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys_common/backtrace.rs:139:18
^[[36mseed2_1    |^[[0m    4: rust_begin_unwind
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:498:5
^[[36mseed2_1    |^[[0m    5: core::panicking::panic_fmt
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/panicking.rs:106:14
^[[36mseed2_1    |^[[0m    6: core::result::unwrap_failed
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/result.rs:1613:5
^[[36mseed2_1    |^[[0m    7: nimiq_block_production::BlockProducer::next_micro_block
^[[36mseed2_1    |^[[0m    8: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
^[[36mseed2_1    |^[[0m    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
^[[36mseed2_1    |^[[0m   10: futures_util::stream::stream::StreamExt::poll_next_unpin
^[[36mseed2_1    |^[[0m   11: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
```

And the following panic was observed in validator3 (seed3 in attached logs)

```
^[[36mseed3_1    |^[[0m ^[[2m2022-03-19T15:28:41.817697Z^[[0m ^[[31mERROR^[[0m ^[[2mpanic               ^[[0m | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: NonExistentAddress { address: Address("20e611f2b035ef8cbfd8cfb575706ef34858f128") }': block-production/src/lib.rs:84
^[[36mseed3_1    |^[[0m    0: log_panics::init::{{closure}}
^[[36mseed3_1    |^[[0m    1: std::panicking::rust_panic_with_hook
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:610:17
^[[36mseed3_1    |^[[0m    2: std::panicking::begin_panic_handler::{{closure}}
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:502:13
^[[36mseed3_1    |^[[0m    3: std::sys_common::backtrace::__rust_end_short_backtrace
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys_common/backtrace.rs:139:18
^[[36mseed3_1    |^[[0m    4: rust_begin_unwind
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:498:5
^[[36mseed3_1    |^[[0m    5: core::panicking::panic_fmt
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/panicking.rs:106:14
^[[36mseed3_1    |^[[0m    6: core::result::unwrap_failed
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/result.rs:1613:5
^[[36mseed3_1    |^[[0m    7: nimiq_block_production::BlockProducer::next_micro_block
^[[36mseed3_1    |^[[0m    8: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
^[[36mseed3_1    |^[[0m    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
^[[36mseed3_1    |^[[0m   10: futures_util::stream::stream::StreamExt::poll_next_unpin
^[[36mseed3_1    |^[[0m   11: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
```

Full logs:

[docker-devnet-logs.tar.gz](https://github.com/nimiq/core-rs-albatross/files/8309600/docker-devnet-logs.tar.gz)

**Comment by viquezclaudio** [comment]
Validator 3 panic is the same observed in #678

**Comment by viquezclaudio** [comment]
Also trying to reproduce this issue, using the same scenario, the following panic was observed:


```
seed2_1    | 2022-03-21T16:18:13.648443Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: AlreadyExistentAddress { address: Address("d6bcc64334e8145da1d4f204f1900b475e6643b9") }': block-production/src/lib.rs:84
seed2_1    |    0: log_panics::init::{{closure}}
seed2_1    |    1: std::panicking::rust_panic_with_hook
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:610:17
seed2_1    |    2: std::panicking::begin_panic_handler::{{closure}}
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:502:13
seed2_1    |    3: std::sys_common::backtrace::__rust_end_short_backtrace
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys_common/backtrace.rs:139:18
seed2_1    |    4: rust_begin_unwind
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:498:5
seed2_1    |    5: core::panicking::panic_fmt
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/panicking.rs:106:14
seed2_1    |    6: core::result::unwrap_failed
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/result.rs:1613:5
seed2_1    |    7: nimiq_block_production::BlockProducer::next_micro_block
seed2_1    |    8: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
seed2_1    |    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
seed2_1    |   10: futures_util::stream::stream::StreamExt::poll_next_unpin
seed2_1    |   11: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
seed2_1    |   12: tokio::runtime::task::core::CoreStage<T>::poll
seed2_1    |   13: tokio::runtime::task::harness::Harness<T,S>::poll
seed2_1    |   14: std::thread::local::LocalKey<T>::with
seed2_1    |   15: tokio::runtime::thread_pool::worker::Context::run_task
seed2_1    |   16: tokio::runtime::thread_pool::worker::Context::run
seed2_1    |   17: tokio::macros::scoped_tls::ScopedKey<T>::set
seed2_1    |   18: tokio::runtime::thread_pool::worker::run
seed2_1    |   19: tokio::runtime::task::harness::Harness<T,S>::poll
seed2_1    |   20: tokio::runtime::blocking::pool::Inner::run
seed2_1    |   21: std::sys_common::backtrace::__rust_begin_short_backtrace
seed2_1    |   22: core::ops::function::FnOnce::call_once{{vtable.shim}}
seed2_1    |   23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/alloc/src/boxed.rs:1691:9
seed2_1    |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/alloc/src/boxed.rs:1691:9
seed2_1    |       std::sys::unix::thread::Thread::new::thread_start
seed2_1    |              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys/unix/thread.rs:106:17
seed2_1    |   24: start_thread
seed2_1    |   25: clone
seed2_1    |     
```


Full logs

[logs.zip](https://github.com/nimiq/core-rs-albatross/files/8317362/logs.zip)
