### ISSUE TITLE
Panic: Failed to compute accounts hash during block production: NonExistentAddress

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#765]
During an execution of the devnet scenario with the enhanced spammer, the following panic was observed:

```
thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: NonExistentAddress { address: Address("2c573a76320fb7b1890559e012b9cc9a17ab706e") }': block-production/src/lib.rs:84
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:502:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:498:5
   5: core::panicking::panic_fmt
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/panicking.rs:106:14
   6: core::result::unwrap_failed
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/result.rs:1613:5
   7: nimiq_block_production::BlockProducer::next_micro_block
   8: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: futures_util::stream::stream::StreamExt::poll_next_unpin
  11: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
  12: tokio::runtime::task::harness::Harness<T,S>::poll
  13: std::thread::local::LocalKey<T>::with
  14: tokio::runtime::thread_pool::worker::Context::run_task
  15: tokio::runtime::thread_pool::worker::Context::run
  16: tokio::macros::scoped_tls::ScopedKey<T>::set
  17: tokio::runtime::thread_pool::worker::run
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  19: tokio::runtime::task::harness::Harness<T,S>::poll
  20: tokio::runtime::blocking::pool::Inner::run
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys/unix/thread.rs:106:17
  24: start_thread
  25: clone

```
[logs.zip](https://github.com/nimiq/core-rs-albatross/files/8446315/logs.zip)

This has been observed with albagen as well. Full logs attached.

**Comment by viquezclaudio** [comment]
The following logs include a print in the mempool update function.
As can be observed in the Validator 3 logs (the one that crashed):

Validator 3 was executing mempool update for block #4040, then it accepted block #4041 and initialized the block producer for block #4042, without executing the mempool update function for block #4041, which means that when it was producing block #4042, the mempool state does not correspond to the blockchain state, in particular, there is a transaction in the mempool that is no longer valid because a sender was pruned/removed due to a transaction in block #4041, so the block producer tries to include a no longer valid transaction in the block and then it crashes:

```
2022-04-14T19:59:06.715022Z DEBUG mmempool          !!## Executing mempool update for 4040
2022-04-14T19:59:06.715048Z DEBUG mmempool          ... Adopted sender: NQ40 GCAA U3UX 8BKD GUN0 PG3T 17HA 4X5H TXVE , recipient NQ50 02GS TAPH QKUN 50CV MUN8 38FP KTUV 1MU2 , value 0.00100
2022-04-14T19:59:06.715120Z DEBUG mmempool          ... Adopted sender: NQ40 GCAA U3UX 8BKD GUN0 PG3T 17HA 4X5H TXVE , recipient NQ94 03AK C8DQ MTYS K024 A5YS 8KCB P3ER 14GC , value 0.00100
2022-04-14T19:59:06.715174Z DEBUG mmempool          ... Adopted sender: NQ40 GCAA U3UX 8BKD GUN0 PG3T 17HA 4X5H TXVE , recipient NQ81 03GU XD97 EECC E9F6 K2VK Q2US 9J6U BSD8 , value 0.00100

.....

2022-04-14T19:59:06.729783Z DEBUG mpush            Accepted block block#4041.0:MI:4f4785d9a2 mnum_transactions=46 kind="extend"
2022-04-14T19:59:06.729911Z DEBUG mvalidator       Initializing block producer for #4042.0
2022-04-14T19:59:06.731074Z INFO  mmicro           [1] Our turn at #4042:0, producing micro block
2022-04-14T19:59:06.731241Z DEBUG mmempool         Returning 46 transactions from mempool (0 remaining)
2022-04-14T19:59:06.731867Z DEBUG mbasic_account    Commit outgoing txn Non existant address NQ10 RNX1 TTTK U0R6 TRPE Q2YF DMB4 1XV3 3RRA
2022-04-14T19:59:06.731890Z DEBUG maccounts         Error commiting senders NonExistentAddress { address: Address("cdbc1def73e0326de6eec0bef6d5640fba31e72a") }
2022-04-14T19:59:06.741864Z ERROR mpanic           thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: NonExistentAddress 

```
