### ISSUE TITLE
Panic detected in CI run (timestamp)

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#875]
In [this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/2447124862) the following panic was detected:
```
2022-06-06T10:57:06.203836Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'assertion failed: current_timestamp >= previous_timestamp': blockchain/src/reward.rs:39
   0: log_panics::init::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:586:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   6: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   7: nimiq_blockchain::blockchain::inherents::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::finalize_previous_batch
   8: nimiq_blockchain::blockchain::inherents::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::create_macro_block_inherents
   9: nimiq_blockchain::blockchain::accounts::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::commit_accounts
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  12: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  13: <nimiq_tendermint::tendermint::Tendermint<DepsTy> as futures_core::stream::Stream>::poll_next
  14: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
  15: futures_util::stream::stream::StreamExt::poll_next_unpin
  16: <futures_util::stream::select_all::SelectAll<St> as futures_core::stream::Stream>::poll_next
  17: <nimiq_tendermint::stream::TendermintStreamWrapper<DepsTy> as futures_core::stream::Stream>::poll_next
  18: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
  19: tokio::runtime::task::core::CoreStage<T>::poll
  20: tokio::runtime::task::harness::poll_future
  21: tokio::runtime::task::harness::Harness<T,S>::poll
  22: std::thread::local::LocalKey<T>::with
  23: tokio::runtime::thread_pool::worker::Context::run_task
  24: tokio::runtime::thread_pool::worker::Context::run
  25: tokio::macros::scoped_tls::ScopedKey<T>::set
  26: tokio::runtime::thread_pool::worker::run
  27: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  28: tokio::runtime::task::harness::Harness<T,S>::poll
  29: tokio::runtime::blocking::pool::Inner::run
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
  33: start_thread
  34: clone
```
Panic was present in logs of Validators 2 and 3 within the `FiveValidatorsWithSpammer` test.

**Comment by Admiiminsupport** [comment]
Kindly open this live chat to talk to the customer service directly on any of of your issues 

https://direct.lc.chat/14201763/
