### ISSUE TITLE
Trie Panic observed during devnet execution

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#936]
During a devnet execution, the following panic was observed in one of the validators:

```
Jul 14 01:17:04 validator3 nimiq-client[1969]: 2022-07-14T01:17:04.731512Z ERROR key_nibbles          | Index 40 exceeds the length of KeyNibbles d6d530da000000000000602dbca99b0000000000, which has length 40.
Jul 14 01:17:04 validator3 nimiq-client[1969]: 2022-07-14T01:17:04.760700Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value': /home/jeffrey/working_dir/nimiq/core-rs-albatross/primitives/trie/src/trie_node.rs:128
Jul 14 01:17:04 validator3 nimiq-client[1969]:    0: log_panics::init::{{closure}}
Jul 14 01:17:04 validator3 nimiq-client[1969]:    1: std::panicking::rust_panic_with_hook
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:702:17
Jul 14 01:17:04 validator3 nimiq-client[1969]:    2: std::panicking::begin_panic_handler::{{closure}}
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:586:13
Jul 14 01:17:04 validator3 nimiq-client[1969]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/sys_common/backtrace.rs:138:18
Jul 14 01:17:04 validator3 nimiq-client[1969]:    4: rust_begin_unwind
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:584:5
Jul 14 01:17:04 validator3 nimiq-client[1969]:    5: core::panicking::panic_fmt
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:142:14
Jul 14 01:17:04 validator3 nimiq-client[1969]:    6: core::panicking::panic
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:48:5
Jul 14 01:17:04 validator3 nimiq-client[1969]:    7: nimiq_trie::trie_node::TrieNode<A>::get_child_index
Jul 14 01:17:04 validator3 nimiq-client[1969]:    8: nimiq_trie::trie_node::TrieNode<A>::put_child
Jul 14 01:17:04 validator3 nimiq-client[1969]:    9: nimiq_trie::trie::MerkleRadixTrie<A>::put
Jul 14 01:17:04 validator3 nimiq-client[1969]:   10: <nimiq_account::basic_account::BasicAccount as nimiq_account::interaction_traits::AccountTransactionInteraction>::commit_incoming_transaction
Jul 14 01:17:04 validator3 nimiq-client[1969]:   11: nimiq_account::accounts::Accounts::commit_batch
Jul 14 01:17:04 validator3 nimiq-client[1969]:   12: nimiq_account::accounts::Accounts::get_root_with
Jul 14 01:17:04 validator3 nimiq-client[1969]:   13: nimiq_block_production::BlockProducer::next_micro_block
Jul 14 01:17:04 validator3 nimiq-client[1969]:   14: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
Jul 14 01:17:04 validator3 nimiq-client[1969]:   15: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::next::{{closure}}
Jul 14 01:17:04 validator3 nimiq-client[1969]:   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 14 01:17:04 validator3 nimiq-client[1969]:   17: futures_util::stream::stream::StreamExt::poll_next_unpin
Jul 14 01:17:04 validator3 nimiq-client[1969]:   18: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
Jul 14 01:17:04 validator3 nimiq-client[1969]:   19: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
Jul 14 01:17:04 validator3 nimiq-client[1969]:   20: tokio::runtime::task::harness::poll_future
Jul 14 01:17:04 validator3 nimiq-client[1969]:   21: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 14 01:17:04 validator3 nimiq-client[1969]:   22: std::thread::local::LocalKey<T>::with
Jul 14 01:17:04 validator3 nimiq-client[1969]:   23: tokio::runtime::thread_pool::worker::Context::run_task
Jul 14 01:17:04 validator3 nimiq-client[1969]:   24: tokio::runtime::thread_pool::worker::Context::run
Jul 14 01:17:04 validator3 nimiq-client[1969]:   25: tokio::macros::scoped_tls::ScopedKey<T>::set
Jul 14 01:17:04 validator3 nimiq-client[1969]:   26: tokio::runtime::thread_pool::worker::run
Jul 14 01:17:04 validator3 nimiq-client[1969]:   27: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Jul 14 01:17:04 validator3 nimiq-client[1969]:   28: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 14 01:17:04 validator3 nimiq-client[1969]:   29: tokio::runtime::blocking::pool::Inner::run
Jul 14 01:17:04 validator3 nimiq-client[1969]:   30: std::sys_common::backtrace::__rust_begin_short_backtrace
Jul 14 01:17:04 validator3 nimiq-client[1969]:   31: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jul 14 01:17:04 validator3 nimiq-client[1969]:   32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1951:9
Jul 14 01:17:04 validator3 nimiq-client[1969]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1951:9
Jul 14 01:17:04 validator3 nimiq-client[1969]:       std::sys::unix::thread::Thread::new::thread_start
Jul 14 01:17:04 validator3 nimiq-client[1969]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/sys/unix/thread.rs:108:17
Jul 14 01:17:04 validator3 nimiq-client[1969]:   33: start_thread
Jul 14 01:17:04 validator3 nimiq-client[1969]:   34: clone
Jul 14 01:17:04 validator3 nimiq-client[1969]:     
```

After further triaging it was determined that this was caused by a discrepancy between the recipient address and the recipient type of a particular transaction. This uncovered a whole class of potential issues that should be taken care of, when accepting or rejecting transactions into the mempool. 

Failing validator logs are attached. 

[do_validator3.log.zip](https://github.com/nimiq/core-rs-albatross/files/9114211/do_validator3.log.zip)

**Comment by viquezclaudio** [comment]
A full solution for this fix will be tracked via issue #944
