### ISSUE TITLE
RPC interface panic during devnet execution

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#947]
In the latest devnet execution a panic was observed in the RPC interface:
```
Jul 19 10:42:28 seed1 nimiq-client[25005]: 2022-07-19T10:42:28.369815Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code': rpc-interface/src/types.rs:629
Jul 19 10:42:28 seed1 nimiq-client[25005]:    0: log_panics::init::{{closure}}
Jul 19 10:42:28 seed1 nimiq-client[25005]:    1: std::panicking::rust_panic_with_hook
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:702:17
Jul 19 10:42:28 seed1 nimiq-client[25005]:    2: std::panicking::begin_panic_handler::{{closure}}
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:586:13
Jul 19 10:42:28 seed1 nimiq-client[25005]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/sys_common/backtrace.rs:138:18
Jul 19 10:42:28 seed1 nimiq-client[25005]:    4: rust_begin_unwind
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/panicking.rs:584:5
Jul 19 10:42:28 seed1 nimiq-client[25005]:    5: core::panicking::panic_fmt
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:142:14
Jul 19 10:42:28 seed1 nimiq-client[25005]:    6: core::panicking::panic
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/core/src/panicking.rs:48:5
Jul 19 10:42:28 seed1 nimiq-client[25005]:    7: nimiq_rpc_interface::types::Account::from_account
Jul 19 10:42:28 seed1 nimiq-client[25005]:    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:    9: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Jul 19 10:42:28 seed1 nimiq-client[25005]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   16: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   17: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   18: <warp::filter::and::AndFuture<T,U> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   19: warp::route::set
Jul 19 10:42:28 seed1 nimiq-client[25005]:   20: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
Jul 19 10:42:28 seed1 nimiq-client[25005]:   21: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
Jul 19 10:42:28 seed1 nimiq-client[25005]:   22: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   23: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
Jul 19 10:42:28 seed1 nimiq-client[25005]:   25: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   26: std::thread::local::LocalKey<T>::with
Jul 19 10:42:28 seed1 nimiq-client[25005]:   27: tokio::runtime::thread_pool::worker::Context::run_task
Jul 19 10:42:28 seed1 nimiq-client[25005]:   28: tokio::runtime::thread_pool::worker::Context::run
Jul 19 10:42:28 seed1 nimiq-client[25005]:   29: tokio::macros::scoped_tls::ScopedKey<T>::set
Jul 19 10:42:28 seed1 nimiq-client[25005]:   30: tokio::runtime::thread_pool::worker::run
Jul 19 10:42:28 seed1 nimiq-client[25005]:   31: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   32: tokio::runtime::task::harness::Harness<T,S>::poll
Jul 19 10:42:28 seed1 nimiq-client[25005]:   33: tokio::runtime::blocking::pool::Inner::run
Jul 19 10:42:28 seed1 nimiq-client[25005]:   34: std::sys_common::backtrace::__rust_begin_short_backtrace
Jul 19 10:42:28 seed1 nimiq-client[25005]:   35: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jul 19 10:42:28 seed1 nimiq-client[25005]:   36: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1951:9
Jul 19 10:42:28 seed1 nimiq-client[25005]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/alloc/src/boxed.rs:1951:9
Jul 19 10:42:28 seed1 nimiq-client[25005]:       std::sys::unix::thread::Thread::new::thread_start
Jul 19 10:42:28 seed1 nimiq-client[25005]:              at /rustc/43347397f7c5ca9a670a3bb3890c7187e24a52ab/library/std/src/sys/unix/thread.rs:108:17
Jul 19 10:42:28 seed1 nimiq-client[25005]:   37: start_thread
```

**Comment by sisou** [comment]
I could have sworn there was a check for this once. And I finally found it. It was removed:
https://github.com/nimiq/core-rs-albatross/commit/ff8eaa4ce3c02c3602923119c38ba20e67393d1c#diff-e4833c94524e86763b0a00d1c4afd44d0212246a34a4fbe72f6bb6907dd9f335L360
