### ISSUE TITLE
Block production panic during devnet execution

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#994]
In the latest devnet execution a panic was observed in the block production's `next_micro_block` function:
```
Aug 13 10:53:22 validator2 nimiq-client[521007]: 2022-08-13T10:53:22.411092Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: InsufficientFunds { needed: Coin(3581960323), balance: Coin(32704) }': block-production/src/lib.rs:84
Aug 13 10:53:22 validator2 nimiq-client[521007]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Aug 13 10:53:22 validator2 nimiq-client[521007]:    1: log_panics::Config::install_panic_hook::{{closure}}
Aug 13 10:53:22 validator2 nimiq-client[521007]:    2: std::panicking::rust_panic_with_hook
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/std/src/panicking.rs:702:17
Aug 13 10:53:22 validator2 nimiq-client[521007]:    3: std::panicking::begin_panic_handler::{{closure}}
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/std/src/panicking.rs:588:13
Aug 13 10:53:22 validator2 nimiq-client[521007]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/std/src/sys_common/backtrace.rs:138:18
Aug 13 10:53:22 validator2 nimiq-client[521007]:    5: rust_begin_unwind
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/std/src/panicking.rs:584:5
Aug 13 10:53:22 validator2 nimiq-client[521007]:    6: core::panicking::panic_fmt
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/panicking.rs:142:14
Aug 13 10:53:22 validator2 nimiq-client[521007]:    7: core::result::unwrap_failed
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/core/src/result.rs:1805:5
Aug 13 10:53:22 validator2 nimiq-client[521007]:    8: nimiq_block_production::BlockProducer::next_micro_block
Aug 13 10:53:22 validator2 nimiq-client[521007]:    9: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
Aug 13 10:53:22 validator2 nimiq-client[521007]:   10: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::next::{{closure}}
Aug 13 10:53:22 validator2 nimiq-client[521007]:   11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Aug 13 10:53:22 validator2 nimiq-client[521007]:   12: futures_util::stream::stream::StreamExt::poll_next_unpin
Aug 13 10:53:22 validator2 nimiq-client[521007]:   13: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
Aug 13 10:53:22 validator2 nimiq-client[521007]:   14: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
Aug 13 10:53:22 validator2 nimiq-client[521007]:   15: tokio::runtime::task::harness::Harness<T,S>::poll
Aug 13 10:53:22 validator2 nimiq-client[521007]:   16: std::thread::local::LocalKey<T>::with
Aug 13 10:53:22 validator2 nimiq-client[521007]:   17: tokio::runtime::thread_pool::worker::Context::run_task
Aug 13 10:53:22 validator2 nimiq-client[521007]:   18: tokio::runtime::thread_pool::worker::Context::run
Aug 13 10:53:22 validator2 nimiq-client[521007]:   19: tokio::macros::scoped_tls::ScopedKey<T>::set
Aug 13 10:53:22 validator2 nimiq-client[521007]:   20: tokio::runtime::thread_pool::worker::run
Aug 13 10:53:22 validator2 nimiq-client[521007]:   21: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Aug 13 10:53:22 validator2 nimiq-client[521007]:   22: tokio::runtime::task::harness::Harness<T,S>::poll
Aug 13 10:53:22 validator2 nimiq-client[521007]:   23: std::sys_common::backtrace::__rust_begin_short_backtrace
Aug 13 10:53:22 validator2 nimiq-client[521007]:   24: core::ops::function::FnOnce::call_once{{vtable.shim}}
Aug 13 10:53:22 validator2 nimiq-client[521007]:   25: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/alloc/src/boxed.rs:1934:9
Aug 13 10:53:22 validator2 nimiq-client[521007]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/alloc/src/boxed.rs:1934:9
Aug 13 10:53:22 validator2 nimiq-client[521007]:       std::sys::unix::thread::Thread::new::thread_start
Aug 13 10:53:22 validator2 nimiq-client[521007]:              at /rustc/495b216696ccbc27c73d6bdc486bf4621d610f4b/library/std/src/sys/unix/thread.rs:108:17
Aug 13 10:53:22 validator2 nimiq-client[521007]:   26: start_thread
Aug 13 10:53:22 validator2 nimiq-client[521007]:   27: clone
```

**Comment by styppo** [comment]
Fixed with #1451.
